/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/greetings.o /home/sensey/Projects/nim-test/nimcache/greetings.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>
typedef struct Sensorfinder144151 Sensorfinder144151;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Sensorals144046 Sensorals144046;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Sensorfinder144151  {
NimStringDesc* path;
};
typedef NIM_CHAR TY113386[256];
struct  Sensorals144046  {
NimStringDesc* path;
NimStringDesc* prefixname;
NimStringDesc* prefixelement;
NimStringDesc* prefixintensity;
};
N_NIMCALL(void, main_145004)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NimStringDesc*, device_144195)(Sensorfinder144151* this_144198, NimStringDesc* name);
static N_INLINE(NIM_BOOL, direxists_127020)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, HEX2F_123481)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, getfilecontents_144021)(NimStringDesc* source);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
static N_INLINE(NIM_BOOL, exists_144054)(Sensorals144046* this_144057);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
static N_INLINE(NI, intencity_144095)(Sensorals144046* this_144098);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NIM_BOOL, enable_144109)(Sensorals144046* this_144112);
N_NIMCALL(NIM_BOOL, parsebool_102305)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, setfilecontents_144033)(NimStringDesc* source, NimStringDesc* value);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sensorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sensorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, greetingsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, greetingsDatInit000)(void);
STRING_LITERAL(TMP583, "/sys/bus/iio/devices", 20);
STRING_LITERAL(TMP584, ".", 1);
STRING_LITERAL(TMP585, "..", 2);
STRING_LITERAL(TMP587, "iio:device", 10);
STRING_LITERAL(TMP588, "/name", 5);
STRING_LITERAL(TMP590, "als", 3);
STRING_LITERAL(TMP591, "\012  0 < len(sensor_path) ", 24);
STRING_LITERAL(TMP592, "/scan_elements", 14);
STRING_LITERAL(TMP593, "/in_intensity_both_raw", 22);
STRING_LITERAL(TMP597, "_en", 3);
STRING_LITERAL(TMP598, "1", 1);
extern TFrame* frameptr_20842;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(NIM_BOOL, direxists_127020)(NimStringDesc* dir) {
	NIM_BOOL result;
	nimfr("dirExists", "os.nim")
	result = 0;
	nimln(233, "os.nim");
	nimln(234, "os.nim");
	result = nosexistsDir(dir);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, device_144195)(Sensorfinder144151* this_144198, NimStringDesc* name) {
	NimStringDesc* result;
	nimfr("device", "sensors.nim")
{	result = 0;
	{
		NimStringDesc* path_144201;
		path_144201 = 0;
		nimln(70, "sensors.nim");
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = direxists_127020((*this_144198).path);
			if (!LOC4) goto LA5;
			{
				NU8 kind_144210;
				NimStringDesc* path_144212;
				NimStringDesc* HEX3Atmp_144214;
				DIR* d_144216;
				kind_144210 = 0;
				path_144212 = 0;
				HEX3Atmp_144214 = 0;
				nimln(71, "sensors.nim");
				HEX3Atmp_144214 = (*this_144198).path;
				nimln(853, "os.nim");
				d_144216 = opendir(HEX3Atmp_144214->data);
				nimln(854, "os.nim");
				{
					int LOC92;
					nimln(349, "system.nim");
					if (!!((d_144216 == NIM_NIL))) goto LA10;
					{
						nimln(855, "os.nim");
						while (1) {
							{
								struct dirent* x_144218;
								NimStringDesc* y_144220;
								nimln(856, "os.nim");
								x_144218 = readdir(d_144216);
								nimln(857, "os.nim");
								{
									if (!(x_144218 == NIM_NIL)) goto LA17;
									goto LA12;
								}
								LA17: ;
								nimln(858, "os.nim");
								y_144220 = cstrToNimstr(((NCSTRING) ((*x_144218).d_name)));
								nimln(859, "os.nim");
								{
									NIM_BOOL LOC21;
									struct stat s_144222;
									NU8 k_144224;
									LOC21 = 0;
									nimln(349, "system.nim");
									LOC21 = !(eqStrings(y_144220, ((NimStringDesc*) &TMP584)));
									if (!(LOC21)) goto LA22;
									LOC21 = !(eqStrings(y_144220, ((NimStringDesc*) &TMP585)));
									LA22: ;
									if (!LOC21) goto LA23;
									memset((void*)(&s_144222), 0, sizeof(s_144222));
									nimln(861, "os.nim");
									{
										if (!NIM_TRUE) goto LA27;
										nimln(862, "os.nim");
										y_144220 = HEX2F_123481(HEX3Atmp_144214, y_144220);
									}
									LA27: ;
									nimln(863, "os.nim");
									k_144224 = ((NU8) 0);
									nimln(866, "os.nim");
									{
										nimln(349, "system.nim");
										if (!!(((*x_144218).d_type == ((NI8) 0)))) goto LA31;
										nimln(867, "os.nim");
										{
											if (!((*x_144218).d_type == ((NI8) 4))) goto LA35;
											k_144224 = ((NU8) 2);
										}
										LA35: ;
										nimln(868, "os.nim");
										{
											if (!((*x_144218).d_type == ((NI8) 10))) goto LA39;
											nimln(869, "os.nim");
											{
												NIM_BOOL LOC43;
												LOC43 = 0;
												LOC43 = direxists_127020(y_144220);
												if (!LOC43) goto LA44;
												k_144224 = ((NU8) 3);
											}
											goto LA41;
											LA44: ;
											{
												NI TMP586;
												nimln(870, "os.nim");
												TMP586 = addInt(k_144224, ((NI) 1));
												if (TMP586 < 0 || TMP586 > 3) raiseOverflow();
												k_144224 = (NU8)(TMP586);
											}
											LA41: ;
										}
										LA39: ;
										nimln(863, "os.nim");
										kind_144210 = k_144224;
										nimln(858, "os.nim");
										path_144212 = y_144220;
										nimln(72, "sensors.nim");
										{
											NI LOC49;
											NimStringDesc* source;
											nimln(349, "system.nim");
											nimln(72, "sensors.nim");
											LOC49 = 0;
											LOC49 = nsuFindStr(path_144212, ((NimStringDesc*) &TMP587), ((NI) 0));
											if (!!((LOC49 == ((NI) -1)))) goto LA50;
											nimln(71, "sensors.nim");
											path_144201 = path_144212;
											nimln(77, "sensors.nim");
											source = nosjoinPath(path_144201, ((NimStringDesc*) &TMP588));
											nimln(78, "sensors.nim");
											{
												NIM_BOOL LOC54;
												LOC54 = 0;
												LOC54 = nosexistsFile(source);
												if (!LOC54) goto LA55;
												nimln(79, "sensors.nim");
												{
													NimStringDesc* LOC59;
													LOC59 = 0;
													LOC59 = getfilecontents_144021(source);
													if (!eqStrings(LOC59, name)) goto LA60;
													nimln(80, "sensors.nim");
													result = copyString(path_144201);
													goto BeforeRet;
												}
												LA60: ;
											}
											LA55: ;
										}
										LA50: ;
										nimln(872, "os.nim");
										goto LA14;
									}
									LA31: ;
									nimln(874, "os.nim");
									{
										int LOC64;
										LOC64 = 0;
										LOC64 = lstat(y_144220->data, (&s_144222));
										if (!(LOC64 < ((NI32) 0))) goto LA65;
										goto LA12;
									}
									LA65: ;
									nimln(875, "os.nim");
									{
										NIM_BOOL LOC69;
										LOC69 = 0;
										LOC69 = S_ISDIR(s_144222.st_mode);
										if (!LOC69) goto LA70;
										k_144224 = ((NU8) 2);
									}
									LA70: ;
									nimln(876, "os.nim");
									{
										NIM_BOOL LOC74;
										NI TMP589;
										LOC74 = 0;
										LOC74 = S_ISLNK(s_144222.st_mode);
										if (!LOC74) goto LA75;
										TMP589 = addInt(k_144224, ((NI) 1));
										if (TMP589 < 0 || TMP589 > 3) raiseOverflow();
										k_144224 = (NU8)(TMP589);
									}
									LA75: ;
									nimln(863, "os.nim");
									kind_144210 = k_144224;
									nimln(858, "os.nim");
									path_144212 = y_144220;
									nimln(72, "sensors.nim");
									{
										NI LOC79;
										NimStringDesc* source_144226;
										nimln(349, "system.nim");
										nimln(72, "sensors.nim");
										LOC79 = 0;
										LOC79 = nsuFindStr(path_144212, ((NimStringDesc*) &TMP587), ((NI) 0));
										if (!!((LOC79 == ((NI) -1)))) goto LA80;
										nimln(71, "sensors.nim");
										path_144201 = path_144212;
										nimln(77, "sensors.nim");
										source_144226 = nosjoinPath(path_144201, ((NimStringDesc*) &TMP588));
										nimln(78, "sensors.nim");
										{
											NIM_BOOL LOC84;
											LOC84 = 0;
											LOC84 = nosexistsFile(source_144226);
											if (!LOC84) goto LA85;
											nimln(79, "sensors.nim");
											{
												NimStringDesc* LOC89;
												LOC89 = 0;
												LOC89 = getfilecontents_144021(source_144226);
												if (!eqStrings(LOC89, name)) goto LA90;
												nimln(80, "sensors.nim");
												result = copyString(path_144201);
												goto BeforeRet;
											}
											LA90: ;
										}
										LA85: ;
									}
									LA80: ;
								}
								LA23: ;
							} LA14: ;
						}
					} LA12: ;
					nimln(878, "os.nim");
					LOC92 = 0;
					LOC92 = closedir(d_144216);
				}
				LA10: ;
			}
		}
		LA5: ;
	}
	nimln(81, "sensors.nim");
	result = copyString(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, exists_144054)(Sensorals144046* this_144057) {
	NIM_BOOL result;
	NimStringDesc* source;
	nimfr("exists", "sensors.nim")
{	result = 0;
	nimln(43, "sensors.nim");
	source = nosjoinPath((*this_144057).path, (*this_144057).prefixelement);
	nimln(44, "sensors.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nosexistsDir(source);
		if (!LOC3) goto LA4;
		{
			NU8 kind_144062;
			NimStringDesc* pathelement_144063;
			DIR* d_144068;
			kind_144062 = 0;
			pathelement_144063 = 0;
			nimln(853, "os.nim");
			d_144068 = opendir(source->data);
			nimln(854, "os.nim");
			{
				int LOC61;
				nimln(349, "system.nim");
				if (!!((d_144068 == NIM_NIL))) goto LA9;
				{
					nimln(855, "os.nim");
					while (1) {
						{
							struct dirent* x_144070;
							NimStringDesc* y_144072;
							nimln(856, "os.nim");
							x_144070 = readdir(d_144068);
							nimln(857, "os.nim");
							{
								if (!(x_144070 == NIM_NIL)) goto LA16;
								goto LA11;
							}
							LA16: ;
							nimln(858, "os.nim");
							y_144072 = cstrToNimstr(((NCSTRING) ((*x_144070).d_name)));
							nimln(859, "os.nim");
							{
								NIM_BOOL LOC20;
								struct stat s_144074;
								NU8 k_144076;
								LOC20 = 0;
								nimln(349, "system.nim");
								LOC20 = !(eqStrings(y_144072, ((NimStringDesc*) &TMP584)));
								if (!(LOC20)) goto LA21;
								LOC20 = !(eqStrings(y_144072, ((NimStringDesc*) &TMP585)));
								LA21: ;
								if (!LOC20) goto LA22;
								memset((void*)(&s_144074), 0, sizeof(s_144074));
								nimln(861, "os.nim");
								{
									if (!NIM_TRUE) goto LA26;
									nimln(862, "os.nim");
									y_144072 = HEX2F_123481(source, y_144072);
								}
								LA26: ;
								nimln(863, "os.nim");
								k_144076 = ((NU8) 0);
								nimln(866, "os.nim");
								{
									nimln(349, "system.nim");
									if (!!(((*x_144070).d_type == ((NI8) 0)))) goto LA30;
									nimln(867, "os.nim");
									{
										if (!((*x_144070).d_type == ((NI8) 4))) goto LA34;
										k_144076 = ((NU8) 2);
									}
									LA34: ;
									nimln(868, "os.nim");
									{
										if (!((*x_144070).d_type == ((NI8) 10))) goto LA38;
										nimln(869, "os.nim");
										{
											NIM_BOOL LOC42;
											LOC42 = 0;
											LOC42 = direxists_127020(y_144072);
											if (!LOC42) goto LA43;
											k_144076 = ((NU8) 3);
										}
										goto LA40;
										LA43: ;
										{
											NI TMP594;
											nimln(870, "os.nim");
											TMP594 = addInt(k_144076, ((NI) 1));
											if (TMP594 < 0 || TMP594 > 3) raiseOverflow();
											k_144076 = (NU8)(TMP594);
										}
										LA40: ;
									}
									LA38: ;
									nimln(863, "os.nim");
									kind_144062 = k_144076;
									nimln(858, "os.nim");
									pathelement_144063 = y_144072;
									nimln(46, "sensors.nim");
									result = nosexistsFile(pathelement_144063);
									goto BeforeRet;
									nimln(872, "os.nim");
									goto LA13;
								}
								LA30: ;
								nimln(874, "os.nim");
								{
									int LOC48;
									LOC48 = 0;
									LOC48 = lstat(y_144072->data, (&s_144074));
									if (!(LOC48 < ((NI32) 0))) goto LA49;
									goto LA11;
								}
								LA49: ;
								nimln(875, "os.nim");
								{
									NIM_BOOL LOC53;
									LOC53 = 0;
									LOC53 = S_ISDIR(s_144074.st_mode);
									if (!LOC53) goto LA54;
									k_144076 = ((NU8) 2);
								}
								LA54: ;
								nimln(876, "os.nim");
								{
									NIM_BOOL LOC58;
									NI TMP595;
									LOC58 = 0;
									LOC58 = S_ISLNK(s_144074.st_mode);
									if (!LOC58) goto LA59;
									TMP595 = addInt(k_144076, ((NI) 1));
									if (TMP595 < 0 || TMP595 > 3) raiseOverflow();
									k_144076 = (NU8)(TMP595);
								}
								LA59: ;
								nimln(863, "os.nim");
								kind_144062 = k_144076;
								nimln(858, "os.nim");
								pathelement_144063 = y_144072;
								nimln(46, "sensors.nim");
								result = nosexistsFile(pathelement_144063);
								goto BeforeRet;
							}
							LA22: ;
						} LA13: ;
					}
				} LA11: ;
				nimln(878, "os.nim");
				LOC61 = 0;
				LOC61 = closedir(d_144068);
			}
			LA9: ;
		}
	}
	LA4: ;
	nimln(47, "sensors.nim");
	result = NIM_FALSE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, intencity_144095)(Sensorals144046* this_144098) {
	NI result;
	NimStringDesc* source;
	nimfr("intencity", "sensors.nim")
{	result = 0;
	nimln(50, "sensors.nim");
	source = nosjoinPath((*this_144098).path, (*this_144098).prefixintensity);
	nimln(51, "sensors.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = nosexistsFile(source);
		if (!LOC3) goto LA4;
		nimln(52, "sensors.nim");
		LOC6 = 0;
		LOC6 = getfilecontents_144021(source);
		result = nsuParseInt(LOC6);
		goto BeforeRet;
	}
	LA4: ;
	nimln(53, "sensors.nim");
	result = ((NI) 0);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, enable_144109)(Sensorals144046* this_144112) {
	NIM_BOOL result;
	NimStringDesc* source;
	nimfr("enable", "sensors.nim")
{	result = 0;
	nimln(56, "sensors.nim");
	source = nosjoinPath((*this_144112).path, (*this_144112).prefixelement);
	nimln(57, "sensors.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nosexistsDir(source);
		if (!LOC3) goto LA4;
		{
			NU8 kind_144117;
			NimStringDesc* pathelement_144118;
			DIR* d_144123;
			kind_144117 = 0;
			pathelement_144118 = 0;
			nimln(853, "os.nim");
			d_144123 = opendir(source->data);
			nimln(854, "os.nim");
			{
				int LOC83;
				nimln(349, "system.nim");
				if (!!((d_144123 == NIM_NIL))) goto LA9;
				{
					nimln(855, "os.nim");
					while (1) {
						{
							struct dirent* x_144125;
							NimStringDesc* y_144127;
							nimln(856, "os.nim");
							x_144125 = readdir(d_144123);
							nimln(857, "os.nim");
							{
								if (!(x_144125 == NIM_NIL)) goto LA16;
								goto LA11;
							}
							LA16: ;
							nimln(858, "os.nim");
							y_144127 = cstrToNimstr(((NCSTRING) ((*x_144125).d_name)));
							nimln(859, "os.nim");
							{
								NIM_BOOL LOC20;
								struct stat s_144129;
								NU8 k_144131;
								LOC20 = 0;
								nimln(349, "system.nim");
								LOC20 = !(eqStrings(y_144127, ((NimStringDesc*) &TMP584)));
								if (!(LOC20)) goto LA21;
								LOC20 = !(eqStrings(y_144127, ((NimStringDesc*) &TMP585)));
								LA21: ;
								if (!LOC20) goto LA22;
								memset((void*)(&s_144129), 0, sizeof(s_144129));
								nimln(861, "os.nim");
								{
									if (!NIM_TRUE) goto LA26;
									nimln(862, "os.nim");
									y_144127 = HEX2F_123481(source, y_144127);
								}
								LA26: ;
								nimln(863, "os.nim");
								k_144131 = ((NU8) 0);
								nimln(866, "os.nim");
								{
									nimln(349, "system.nim");
									if (!!(((*x_144125).d_type == ((NI8) 0)))) goto LA30;
									nimln(867, "os.nim");
									{
										if (!((*x_144125).d_type == ((NI8) 4))) goto LA34;
										k_144131 = ((NU8) 2);
									}
									LA34: ;
									nimln(868, "os.nim");
									{
										if (!((*x_144125).d_type == ((NI8) 10))) goto LA38;
										nimln(869, "os.nim");
										{
											NIM_BOOL LOC42;
											LOC42 = 0;
											LOC42 = direxists_127020(y_144127);
											if (!LOC42) goto LA43;
											k_144131 = ((NU8) 3);
										}
										goto LA40;
										LA43: ;
										{
											NI TMP596;
											nimln(870, "os.nim");
											TMP596 = addInt(k_144131, ((NI) 1));
											if (TMP596 < 0 || TMP596 > 3) raiseOverflow();
											k_144131 = (NU8)(TMP596);
										}
										LA40: ;
									}
									LA38: ;
									nimln(863, "os.nim");
									kind_144117 = k_144131;
									nimln(858, "os.nim");
									pathelement_144118 = y_144127;
									nimln(59, "sensors.nim");
									{
										NI LOC48;
										nimln(349, "system.nim");
										nimln(59, "sensors.nim");
										LOC48 = 0;
										LOC48 = nsuFindStr(pathelement_144118, ((NimStringDesc*) &TMP597), ((NI) 0));
										if (!!((LOC48 == ((NI) -1)))) goto LA49;
										nimln(60, "sensors.nim");
										{
											NimStringDesc* LOC53;
											NIM_BOOL LOC54;
											LOC53 = 0;
											LOC53 = getfilecontents_144021(pathelement_144118);
											LOC54 = 0;
											LOC54 = parsebool_102305(LOC53);
											if (!!(LOC54)) goto LA55;
											nimln(61, "sensors.nim");
											result = setfilecontents_144033(pathelement_144118, ((NimStringDesc*) &TMP598));
											goto BeforeRet;
										}
										LA55: ;
									}
									LA49: ;
									nimln(872, "os.nim");
									goto LA13;
								}
								LA30: ;
								nimln(874, "os.nim");
								{
									int LOC59;
									LOC59 = 0;
									LOC59 = lstat(y_144127->data, (&s_144129));
									if (!(LOC59 < ((NI32) 0))) goto LA60;
									goto LA11;
								}
								LA60: ;
								nimln(875, "os.nim");
								{
									NIM_BOOL LOC64;
									LOC64 = 0;
									LOC64 = S_ISDIR(s_144129.st_mode);
									if (!LOC64) goto LA65;
									k_144131 = ((NU8) 2);
								}
								LA65: ;
								nimln(876, "os.nim");
								{
									NIM_BOOL LOC69;
									NI TMP599;
									LOC69 = 0;
									LOC69 = S_ISLNK(s_144129.st_mode);
									if (!LOC69) goto LA70;
									TMP599 = addInt(k_144131, ((NI) 1));
									if (TMP599 < 0 || TMP599 > 3) raiseOverflow();
									k_144131 = (NU8)(TMP599);
								}
								LA70: ;
								nimln(863, "os.nim");
								kind_144117 = k_144131;
								nimln(858, "os.nim");
								pathelement_144118 = y_144127;
								nimln(59, "sensors.nim");
								{
									NI LOC74;
									nimln(349, "system.nim");
									nimln(59, "sensors.nim");
									LOC74 = 0;
									LOC74 = nsuFindStr(pathelement_144118, ((NimStringDesc*) &TMP597), ((NI) 0));
									if (!!((LOC74 == ((NI) -1)))) goto LA75;
									nimln(60, "sensors.nim");
									{
										NimStringDesc* LOC79;
										NIM_BOOL LOC80;
										LOC79 = 0;
										LOC79 = getfilecontents_144021(pathelement_144118);
										LOC80 = 0;
										LOC80 = parsebool_102305(LOC79);
										if (!!(LOC80)) goto LA81;
										nimln(61, "sensors.nim");
										result = setfilecontents_144033(pathelement_144118, ((NimStringDesc*) &TMP598));
										goto BeforeRet;
									}
									LA81: ;
								}
								LA75: ;
							}
							LA22: ;
						} LA13: ;
					}
				} LA11: ;
				nimln(878, "os.nim");
				LOC83 = 0;
				LOC83 = closedir(d_144123);
			}
			LA9: ;
		}
	}
	LA4: ;
	nimln(62, "sensors.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, main_145004)(void) {
	Sensorfinder144151 finder;
	Sensorfinder144151 LOC1;
	NimStringDesc* sensorpath;
	Sensorals144046 sensor;
	Sensorals144046 LOC6;
	NIM_BOOL LOC7;
	NimStringDesc* LOC8;
	NI LOC9;
	NimStringDesc* LOC10;
	NIM_BOOL LOC11;
	NimStringDesc* LOC12;
	nimfr("main", "greetings.nim")
	memset((void*)(&finder), 0, sizeof(finder));
	nimln(22, "greetings.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.path = copyString(((NimStringDesc*) &TMP583));
	finder.path = LOC1.path;
	nimln(23, "greetings.nim");
	sensorpath = device_144195((&finder), ((NimStringDesc*) &TMP590));
	nimln(24, "greetings.nim");
	{
		if (!!((((NI) 0) < (sensorpath ? sensorpath->Sup.len : 0)))) goto LA4;
		failedassertimpl_91603(((NimStringDesc*) &TMP591));
	}
	LA4: ;
	memset((void*)(&sensor), 0, sizeof(sensor));
	nimln(26, "greetings.nim");
	memset((void*)(&LOC6), 0, sizeof(LOC6));
	memset((void*)(&LOC6), 0, sizeof(LOC6));
	LOC6.path = copyString(sensorpath);
	LOC6.prefixname = copyString(((NimStringDesc*) &TMP588));
	LOC6.prefixelement = copyString(((NimStringDesc*) &TMP592));
	LOC6.prefixintensity = copyString(((NimStringDesc*) &TMP593));
	sensor.path = LOC6.path;
	sensor.prefixname = LOC6.prefixname;
	sensor.prefixelement = LOC6.prefixelement;
	sensor.prefixintensity = LOC6.prefixintensity;
	nimln(32, "greetings.nim");
	LOC7 = 0;
	LOC7 = exists_144054((&sensor));
	LOC8 = 0;
	LOC8 = nimBoolToStr(LOC7);
	printf("%s\012", LOC8? (LOC8)->data:"nil");
	nimln(33, "greetings.nim");
	LOC9 = 0;
	LOC9 = intencity_144095((&sensor));
	LOC10 = 0;
	LOC10 = nimIntToStr(LOC9);
	printf("%s\012", LOC10? (LOC10)->data:"nil");
	nimln(34, "greetings.nim");
	LOC11 = 0;
	LOC11 = enable_144109((&sensor));
	LOC12 = 0;
	LOC12 = nimBoolToStr(LOC11);
	printf("%s\012", LOC12? (LOC12)->data:"nil");
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_parseutilsDatInit000();
	HEX00_strutilsDatInit000();
	HEX00_timesDatInit000();
	HEX00_posixDatInit000();
	HEX00_osDatInit000();
	HEX00_streamsDatInit000();
	HEX00_sensorsDatInit000();
	greetingsDatInit000();
	HEX00_parseutilsInit000();
	HEX00_strutilsInit000();
	HEX00_timesInit000();
	HEX00_posixInit000();
	HEX00_osInit000();
	HEX00_streamsInit000();
	HEX00_sensorsInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	greetingsInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, greetingsInit000)(void) {
	nimfr("greetings", "greetings.nim")
	nimln(37, "greetings.nim");
	main_145004();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, greetingsDatInit000)(void) {
}

