/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/lexbase.o /home/sensey/Projects/nim-test/nimcache/lexbase.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Baselexer162032 Baselexer162032;
typedef struct TNimObject TNimObject;
typedef struct Streamobj140227 Streamobj140227;
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef NU8 TY162040[32];
struct  Baselexer162032  {
  TNimObject Sup;
NI bufpos;
NCSTRING buf;
NI buflen;
Streamobj140227* input;
NI linenumber;
NI sentinel;
NI linestart;
TY162040 refillchars;
};
typedef N_NIMCALL_PTR(void, TY140228) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY140232) (Streamobj140227* s);
typedef N_NIMCALL_PTR(void, TY140236) (Streamobj140227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY140241) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NI, TY140245) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY140251) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140257) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140263) (Streamobj140227* s);
struct  Streamobj140227  {
  TNimObject Sup;
TY140228 closeimpl;
TY140232 atendimpl;
TY140236 setpositionimpl;
TY140241 getpositionimpl;
TY140245 readdataimpl;
TY140251 peekdataimpl;
TY140257 writedataimpl;
TY140263 flushimpl;
};
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NOCONV(void*, alloc_8401)(NI size);
N_NIMCALL(void, fillbuffer_162064)(Baselexer162032* L);
N_NIMCALL(NI, readdata_140380)(Streamobj140227* s, void* buffer, NI buflen);
N_NOCONV(void*, realloc_8433)(void* p, NI newsize);
N_NIMCALL(void, skiputf8bom_163607)(Baselexer162032* L);
N_NIMCALL(NI, fillbaselexer_162827)(Baselexer162032* L, NI pos);
N_NOCONV(void, dealloc_8448)(void* p);
N_NIMCALL(void, close_140291)(Streamobj140227* s);
extern TNimType NTI4011; /* RootObj */
TNimType NTI162032; /* BaseLexer */
extern TNimType NTI108; /* int */
extern TNimType NTI151; /* cstring */
extern TNimType NTI140225; /* Stream */
extern TNimType NTI147; /* char */
TNimType NTI162040; /* set[char] */

N_NIMCALL(void, fillbuffer_162064)(Baselexer162032* L) {
	NI charsread;
	NI tocopy;
	NI s;
	NI oldbuflen;
	NI LOC5;
	charsread = 0;
	tocopy = 0;
	s = 0;
	oldbuflen = 0;
	tocopy = (NI)((NI)((*L).buflen - (*L).sentinel) - ((NI) 1));
	{
		if (!(((NI) 0) < tocopy)) goto LA3;
		memmove(((void*) ((*L).buf)), ((void*) ((&(*L).buf[(NI)((*L).sentinel + ((NI) 1))]))), ((NI) ((NI)(tocopy * ((NI) 1)))));
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = readdata_140380((*L).input, ((void*) ((&(*L).buf[tocopy]))), (NI)((NI)((*L).sentinel + ((NI) 1)) * ((NI) 1)));
	charsread = (NI)(LOC5 / ((NI) 1));
	s = (NI)(tocopy + charsread);
	{
		if (!(charsread < (NI)((*L).sentinel + ((NI) 1)))) goto LA8;
		(*L).buf[s] = 0;
		(*L).sentinel = s;
	}
	goto LA6;
	LA8: ;
	{
		s -= ((NI) 1);
		{
			while (1) {
				{
					while (1) {
						NIM_BOOL LOC15;
						LOC15 = 0;
						LOC15 = (((NI) 0) <= s);
						if (!(LOC15)) goto LA16;
						LOC15 = !((((*L).refillchars[((NU8)((*L).buf[s]))/8] &(1<<(((NU8)((*L).buf[s]))%8)))!=0));
						LA16: ;
						if (!LOC15) goto LA14;
						s -= ((NI) 1);
					} LA14: ;
				}
				{
					if (!(((NI) 0) <= s)) goto LA19;
					(*L).sentinel = s;
					goto LA11;
				}
				goto LA17;
				LA19: ;
				{
					void* LOC22;
					NI LOC23;
					oldbuflen = (*L).buflen;
					(*L).buflen = (NI)((*L).buflen * ((NI) 2));
					LOC22 = 0;
					LOC22 = realloc_8433(((void*) ((*L).buf)), ((NI) ((NI)((*L).buflen * ((NI) 1)))));
					(*L).buf = ((NCSTRING) (LOC22));
					LOC23 = 0;
					LOC23 = readdata_140380((*L).input, ((void*) ((&(*L).buf[oldbuflen]))), (NI)(oldbuflen * ((NI) 1)));
					charsread = (NI)(LOC23 / ((NI) 1));
					{
						if (!(charsread < oldbuflen)) goto LA26;
						(*L).buf[(NI)(oldbuflen + charsread)] = 0;
						(*L).sentinel = (NI)(oldbuflen + charsread);
						goto LA11;
					}
					LA26: ;
					s = (NI)((*L).buflen - ((NI) 1));
				}
				LA17: ;
			}
		} LA11: ;
	}
	LA6: ;
}

N_NIMCALL(void, skiputf8bom_163607)(Baselexer162032* L) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		LOC3 = 0;
		LOC4 = 0;
		LOC4 = ((NU8)((*L).buf[((NI) 0)]) == (NU8)(239));
		if (!(LOC4)) goto LA5;
		LOC4 = ((NU8)((*L).buf[((NI) 1)]) == (NU8)(187));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		LOC3 = ((NU8)((*L).buf[((NI) 2)]) == (NU8)(191));
		LA6: ;
		if (!LOC3) goto LA7;
		(*L).bufpos += ((NI) 3);
		(*L).linestart += ((NI) 3);
	}
	LA7: ;
}

N_NIMCALL(void, open_163635)(Baselexer162032* L, Streamobj140227* input, NI buflen, TY162040 refillchars) {
	void* LOC1;
	unsureAsgnRef((void**) (&(*L).input), input);
	(*L).bufpos = ((NI) 0);
	(*L).buflen = buflen;
	memcpy((void*)(*L).refillchars, (NIM_CONST void*)refillchars, 32);
	LOC1 = 0;
	LOC1 = alloc_8401(((NI) ((NI)(buflen * ((NI) 1)))));
	(*L).buf = ((NCSTRING) (LOC1));
	(*L).sentinel = (NI)(buflen - ((NI) 1));
	(*L).linestart = ((NI) 0);
	(*L).linenumber = ((NI) 1);
	fillbuffer_162064(L);
	skiputf8bom_163607(L);
}

N_NIMCALL(NI, fillbaselexer_162827)(Baselexer162032* L, NI pos) {
	NI result;
	result = 0;
	{
		if (!(pos < (*L).sentinel)) goto LA3;
		result = (NI)(pos + ((NI) 1));
	}
	goto LA1;
	LA3: ;
	{
		fillbuffer_162064(L);
		(*L).bufpos = ((NI) 0);
		result = ((NI) 0);
	}
	LA1: ;
	return result;
}

N_NIMCALL(NI, handlecr_163007)(Baselexer162032* L, NI pos) {
	NI result;
	result = 0;
	(*L).linenumber += ((NI) 1);
	result = fillbaselexer_162827(L, pos);
	{
		if (!((NU8)((*L).buf[result]) == (NU8)(10))) goto LA3;
		result = fillbaselexer_162827(L, result);
	}
	LA3: ;
	(*L).linestart = result;
	return result;
}

N_NIMCALL(NI, handlelf_163216)(Baselexer162032* L, NI pos) {
	NI result;
	result = 0;
	(*L).linenumber += ((NI) 1);
	result = fillbaselexer_162827(L, pos);
	(*L).linestart = result;
	return result;
}

N_NIMCALL(NI, getcolnumber_164008)(Baselexer162032* L, NI pos) {
	NI result;
	result = 0;
	result = ((NI)(pos - (*L).linestart) > 0? ((NI)(pos - (*L).linestart)) : -((NI)(pos - (*L).linestart)));
	return result;
}

N_NIMCALL(void, close_162054)(Baselexer162032* L) {
	dealloc_8448(((void*) ((*L).buf)));
	close_140291((*L).input);
}
NIM_EXTERNC N_NOINLINE(void, HEX00_lexbaseInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_lexbaseDatInit000)(void) {
static TNimNode* TMP113[8];
static TNimNode TMP39[10];
NTI162032.size = sizeof(Baselexer162032);
NTI162032.kind = 17;
NTI162032.base = (&NTI4011);
TMP113[0] = &TMP39[1];
TMP39[1].kind = 1;
TMP39[1].offset = offsetof(Baselexer162032, bufpos);
TMP39[1].typ = (&NTI108);
TMP39[1].name = "bufpos";
TMP113[1] = &TMP39[2];
TMP39[2].kind = 1;
TMP39[2].offset = offsetof(Baselexer162032, buf);
TMP39[2].typ = (&NTI151);
TMP39[2].name = "buf";
TMP113[2] = &TMP39[3];
TMP39[3].kind = 1;
TMP39[3].offset = offsetof(Baselexer162032, buflen);
TMP39[3].typ = (&NTI108);
TMP39[3].name = "bufLen";
TMP113[3] = &TMP39[4];
TMP39[4].kind = 1;
TMP39[4].offset = offsetof(Baselexer162032, input);
TMP39[4].typ = (&NTI140225);
TMP39[4].name = "input";
TMP113[4] = &TMP39[5];
TMP39[5].kind = 1;
TMP39[5].offset = offsetof(Baselexer162032, linenumber);
TMP39[5].typ = (&NTI108);
TMP39[5].name = "lineNumber";
TMP113[5] = &TMP39[6];
TMP39[6].kind = 1;
TMP39[6].offset = offsetof(Baselexer162032, sentinel);
TMP39[6].typ = (&NTI108);
TMP39[6].name = "sentinel";
TMP113[6] = &TMP39[7];
TMP39[7].kind = 1;
TMP39[7].offset = offsetof(Baselexer162032, linestart);
TMP39[7].typ = (&NTI108);
TMP39[7].name = "lineStart";
TMP113[7] = &TMP39[8];
NTI162040.size = sizeof(TY162040);
NTI162040.kind = 19;
NTI162040.base = (&NTI147);
NTI162040.flags = 3;
TMP39[9].len = 0; TMP39[9].kind = 0;
NTI162040.node = &TMP39[9];
TMP39[8].kind = 1;
TMP39[8].offset = offsetof(Baselexer162032, refillchars);
TMP39[8].typ = (&NTI162040);
TMP39[8].name = "refillChars";
TMP39[0].len = 8; TMP39[0].kind = 2; TMP39[0].sons = &TMP113[0];
NTI162032.node = &TMP39[0];
}

