/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/logging.o /home/sensey/Projects/nim-test/nimcache/logging.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <setjmp.h>
typedef struct LoggerHEX3Aobjecttype168052 LoggerHEX3Aobjecttype168052;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct ConsoleloggerHEX3Aobjecttype168056 ConsoleloggerHEX3Aobjecttype168056;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY122809 TY122809;
typedef struct FileloggerHEX3Aobjecttype168058 FileloggerHEX3Aobjecttype168058;
typedef struct RollingfileloggerHEX3Aobjecttype168061 RollingfileloggerHEX3Aobjecttype168061;
typedef struct TY168632 TY168632;
typedef struct Cell48947 Cell48947;
typedef struct Cellseq48963 Cellseq48963;
typedef struct Gcheap51018 Gcheap51018;
typedef struct Gcstack51016 Gcstack51016;
typedef struct Cellset48959 Cellset48959;
typedef struct Pagedesc48955 Pagedesc48955;
typedef struct Memregion30891 Memregion30891;
typedef struct Smallchunk30843 Smallchunk30843;
typedef struct Llchunk30885 Llchunk30885;
typedef struct Bigchunk30845 Bigchunk30845;
typedef struct Intset30817 Intset30817;
typedef struct Trunk30813 Trunk30813;
typedef struct Avlnode30889 Avlnode30889;
typedef struct Gcstat51014 Gcstat51014;
typedef struct Slice90370 Slice90370;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Basechunk30841 Basechunk30841;
typedef struct Freecell30833 Freecell30833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  LoggerHEX3Aobjecttype168052  {
  TNimObject Sup;
NU8 levelthreshold;
NimStringDesc* fmtstr;
};
struct  ConsoleloggerHEX3Aobjecttype168056  {
  LoggerHEX3Aobjecttype168052 Sup;
};
typedef NimStringDesc* TY168231[1];
struct TY122809 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NimStringDesc* TY168036[7];
struct  FileloggerHEX3Aobjecttype168058  {
  LoggerHEX3Aobjecttype168052 Sup;
FILE* file;
};
struct  RollingfileloggerHEX3Aobjecttype168061  {
  FileloggerHEX3Aobjecttype168058 Sup;
NI maxlines;
NI curline;
NimStringDesc* basename;
NU8 basemode;
NI logfiles;
NI bufsize;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell48947  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48963  {
NI len;
NI cap;
Cell48947** d;
};
struct  Cellset48959  {
NI counter;
NI max;
Pagedesc48955* head;
Pagedesc48955** data;
};
typedef Smallchunk30843* TY30906[512];
typedef Trunk30813* Trunkbuckets30815[256];
struct  Intset30817  {
Trunkbuckets30815 data;
};
struct  Memregion30891  {
NI minlargeobj;
NI maxlargeobj;
TY30906 freesmallchunks;
Llchunk30885* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30845* freechunkslist;
Intset30817 chunkstarts;
Avlnode30889* root;
Avlnode30889* deleted;
Avlnode30889* last;
Avlnode30889* freeavlnodes;
};
struct  Gcstat51014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51018  {
Gcstack51016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48963 zct;
Cellseq48963 decstack;
Cellset48959 cycleroots;
Cellseq48963 tempstack;
NI recgclock;
Memregion30891 region;
Gcstat51014 stat;
};
typedef NIM_CHAR TY112386[256];
struct  Slice90370  {
NI a;
NI b;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
struct  Gcstack51016  {
Gcstack51016* prev;
Gcstack51016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30822[8];
struct  Pagedesc48955  {
Pagedesc48955* next;
NI key;
TY30822 bits;
};
struct  Basechunk30841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30843  {
  Basechunk30841 Sup;
Smallchunk30843* next;
Smallchunk30843* prev;
Freecell30833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30885  {
NI size;
NI acc;
Llchunk30885* next;
};
struct  Bigchunk30845  {
  Basechunk30841 Sup;
Bigchunk30845* next;
Bigchunk30845* prev;
NI align;
NF data;
};
struct  Trunk30813  {
Trunk30813* next;
NI key;
TY30822 bits;
};
typedef Avlnode30889* TY30896[2];
struct  Avlnode30889  {
TY30896 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30833  {
Freecell30833* next;
NI zerofield;
};
struct TY168632 {
  TGenericSeq Sup;
  LoggerHEX3Aobjecttype168052* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, log_168201)(LoggerHEX3Aobjecttype168052* logger, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, log_168216)(ConsoleloggerHEX3Aobjecttype168056* logger, NU8 level, NimStringDesc** args, NI argsLen0);
static N_INLINE(void, writeline_168235)(FILE* f, NimStringDesc** x, NI xLen0);
N_NIMCALL(void, write_16895)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, substitutelog_168080)(NimStringDesc* frmt, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY122809* Result);
N_NIMCALL(void, log_168289)(FileloggerHEX3Aobjecttype168058* logger, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, log_168565)(RollingfileloggerHEX3Aobjecttype168061* logger, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, rotate_168523)(RollingfileloggerHEX3Aobjecttype168061* logger);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, nosmoveFile)(NimStringDesc* source, NimStringDesc* dest);
N_NIMCALL(NimStringDesc*, HEX2F_122481)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(FILE*, open_16817)(NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, log_168211)(LoggerHEX3Aobjecttype168052* logger, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP152)(void* p, NI op);
N_NIMCALL(void, TMP153)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_54604)(Cell48947* c);
static N_INLINE(void, rtladdzct_54204)(Cell48947* c);
N_NOINLINE(void, addzct_52617)(Cellseq48963* s, Cell48947* c);
static N_INLINE(NIM_BOOL, canbecycleroot_52667)(Cell48947* c);
static N_INLINE(void, rtladdcycleroot_53423)(Cell48947* c);
N_NOINLINE(void, incl_49665)(Cellset48959* s, Cell48947* cell);
static N_INLINE(Cell48947*, usrtocell_52646)(void* usr);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55022)(Cell48947* c);
N_NIMCALL(void, TMP158)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NI, countfiles_168421)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, direxists_126020)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_90363)(NimStringDesc* s, Slice90370 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_81016, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice90370, HEX2EHEX2E_104291)(NI a, NI b);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NI, countloglines_168386)(RollingfileloggerHEX3Aobjecttype168061* logger);
N_NIMCALL(NIM_BOOL, readline_16919)(FILE* f, NimStringDesc** line);
STRING_LITERAL(TMP48, "\012", 1);
STRING_LITERAL(TMP49, "", 0);
STRING_LITERAL(TMP58, "date", 4);
STRING_LITERAL(TMP59, "time", 4);
STRING_LITERAL(TMP60, "datetime", 8);
STRING_LITERAL(TMP61, "app", 3);
STRING_LITERAL(TMP62, "appdir", 6);
STRING_LITERAL(TMP63, "appname", 7);
STRING_LITERAL(TMP64, "levelid", 7);
STRING_LITERAL(TMP65, "levelname", 9);
STRING_LITERAL(TMP76, "T", 1);
STRING_LITERAL(TMP77, "DEBUG", 5);
STRING_LITERAL(TMP78, "INFO", 4);
STRING_LITERAL(TMP79, "WARN", 4);
STRING_LITERAL(TMP80, "ERROR", 5);
STRING_LITERAL(TMP81, "FATAL", 5);
STRING_LITERAL(TMP82, "NONE", 4);
NIM_CONST TY168036 Levelnames_168033 = {((NimStringDesc*) &TMP77),
((NimStringDesc*) &TMP77),
((NimStringDesc*) &TMP78),
((NimStringDesc*) &TMP79),
((NimStringDesc*) &TMP80),
((NimStringDesc*) &TMP81),
((NimStringDesc*) &TMP82)}
;
STRING_LITERAL(TMP159, ".", 1);
STRING_LITERAL(TMP160, "..", 2);
NU8 level_168627;
TY168632* handlers_168633;
extern TNimType NTI4011; /* RootObj */
TNimType NTI168052; /* Logger:ObjectType */
TNimType NTI168022; /* Level */
extern TNimType NTI149; /* string */
TNimType NTI168045; /* Logger */
TNimType NTI168632; /* seq[Logger] */
extern Gcheap51018 gch_51059;
TNimType NTI168058; /* FileLogger:ObjectType */
extern TNimType NTI16404; /* File */
TNimType NTI168061; /* RollingFileLogger:ObjectType */
extern TNimType NTI108; /* int */
extern TNimType NTI16406; /* FileMode */
TNimType NTI168051; /* RollingFileLogger */
extern TSafePoint* exchandler_20843;
extern TNimType NTI4049; /* ValueError */
extern Exception* currexception_20845;
TNimType NTI168056; /* ConsoleLogger:ObjectType */

N_NIMCALL(void, log_168201)(LoggerHEX3Aobjecttype168052* logger, NU8 level, NimStringDesc** args, NI argsLen0) {
}

static N_INLINE(void, writeline_168235)(FILE* f, NimStringDesc** x, NI xLen0) {
	{
		NimStringDesc* i_168251;
		NI i_168259;
		i_168251 = 0;
		i_168259 = ((NI) 0);
		{
			while (1) {
				if (!(i_168259 < xLen0)) goto LA3;
				i_168251 = x[i_168259];
				write_16895(f, i_168251);
				i_168259 += ((NI) 1);
			} LA3: ;
		}
	}
	write_16895(f, ((NimStringDesc*) &TMP48));
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, substitutelog_168080)(NimStringDesc* frmt, NU8 level, NimStringDesc** args, NI argsLen0) {
	NimStringDesc* result;
	NI msglen;
	NI i;
	result = 0;
	msglen = ((NI) 0);
	{
		NimStringDesc* arg_168096;
		NI i_168158;
		arg_168096 = 0;
		i_168158 = ((NI) 0);
		{
			while (1) {
				if (!(i_168158 < argsLen0)) goto LA3;
				arg_168096 = args[i_168158];
				msglen += (arg_168096 ? arg_168096->Sup.len : 0);
				i_168158 += ((NI) 1);
			} LA3: ;
		}
	}
	result = rawNewString(((NI) ((NI)((NI)((frmt ? frmt->Sup.len : 0) + msglen) + ((NI) 20)))));
	i = ((NI) 0);
	{
		while (1) {
			if (!(i < (frmt ? frmt->Sup.len : 0))) goto LA5;
			{
				if (!!(((NU8)(frmt->data[i]) == (NU8)(36)))) goto LA8;
				result = addChar(result, frmt->data[i]);
				i += ((NI) 1);
			}
			goto LA6;
			LA8: ;
			{
				NimStringDesc* v;
				NimStringDesc* app;
				i += ((NI) 1);
				v = copyString(((NimStringDesc*) &TMP49));
				app = nosgetAppFilename();
				{
					while (1) {
						NIM_CHAR LOC13;
						if (!(((NU8)(frmt->data[i])) >= ((NU8)(97)) && ((NU8)(frmt->data[i])) <= ((NU8)(122)) || ((NU8)(frmt->data[i])) >= ((NU8)(65)) && ((NU8)(frmt->data[i])) <= ((NU8)(90)) || ((NU8)(frmt->data[i])) >= ((NU8)(48)) && ((NU8)(frmt->data[i])) <= ((NU8)(57)) || ((NU8)(frmt->data[i])) == ((NU8)(95)))) goto LA12;
						LOC13 = 0;
						LOC13 = nsuToLowerChar(frmt->data[i]);
						v = addChar(v, LOC13);
						i += ((NI) 1);
					} LA12: ;
				}
				if (eqStrings(v, ((NimStringDesc*) &TMP58))) goto LA14;
				if (eqStrings(v, ((NimStringDesc*) &TMP59))) goto LA15;
				if (eqStrings(v, ((NimStringDesc*) &TMP60))) goto LA16;
				if (eqStrings(v, ((NimStringDesc*) &TMP61))) goto LA17;
				if (eqStrings(v, ((NimStringDesc*) &TMP62))) goto LA18;
				if (eqStrings(v, ((NimStringDesc*) &TMP63))) goto LA19;
				if (eqStrings(v, ((NimStringDesc*) &TMP64))) goto LA20;
				if (eqStrings(v, ((NimStringDesc*) &TMP65))) goto LA21;
				goto LA22;
				LA14: ;
				{
					NimStringDesc* LOC25;
					LOC25 = 0;
					LOC25 = ntgetDateStr();
					result = resizeString(result, LOC25->Sup.len + 0);
appendString(result, LOC25);
				}
				goto LA23;
				LA15: ;
				{
					NimStringDesc* LOC27;
					LOC27 = 0;
					LOC27 = ntgetClockStr();
					result = resizeString(result, LOC27->Sup.len + 0);
appendString(result, LOC27);
				}
				goto LA23;
				LA16: ;
				{
					NimStringDesc* LOC29;
					NimStringDesc* LOC30;
					NimStringDesc* LOC31;
					LOC29 = 0;
					LOC30 = 0;
					LOC30 = ntgetDateStr();
					LOC31 = 0;
					LOC31 = ntgetClockStr();
					LOC29 = rawNewString(LOC30->Sup.len + LOC31->Sup.len + 1);
appendString(LOC29, LOC30);
appendString(LOC29, ((NimStringDesc*) &TMP76));
appendString(LOC29, LOC31);
					result = resizeString(result, LOC29->Sup.len + 0);
appendString(result, LOC29);
				}
				goto LA23;
				LA17: ;
				{
					result = resizeString(result, app->Sup.len + 0);
appendString(result, app);
				}
				goto LA23;
				LA18: ;
				{
					TY122809 LOC34;
					memset((void*)(&LOC34), 0, sizeof(LOC34));
					nossplitFile(app, (&LOC34));
					result = resizeString(result, LOC34.Field0->Sup.len + 0);
appendString(result, LOC34.Field0);
				}
				goto LA23;
				LA19: ;
				{
					TY122809 LOC36;
					memset((void*)(&LOC36), 0, sizeof(LOC36));
					nossplitFile(app, (&LOC36));
					result = resizeString(result, LOC36.Field1->Sup.len + 0);
appendString(result, LOC36.Field1);
				}
				goto LA23;
				LA20: ;
				{
					result = addChar(result, Levelnames_168033[(level)- 0]->data[((NI) 0)]);
				}
				goto LA23;
				LA21: ;
				{
					result = resizeString(result, Levelnames_168033[(level)- 0]->Sup.len + 0);
appendString(result, Levelnames_168033[(level)- 0]);
				}
				goto LA23;
				LA22: ;
				{
				}
				LA23: ;
			}
			LA6: ;
		} LA5: ;
	}
	{
		NimStringDesc* arg_168154;
		NI i_168164;
		arg_168154 = 0;
		i_168164 = ((NI) 0);
		{
			while (1) {
				if (!(i_168164 < argsLen0)) goto LA42;
				arg_168154 = args[i_168164];
				result = resizeString(result, arg_168154->Sup.len + 0);
appendString(result, arg_168154);
				i_168164 += ((NI) 1);
			} LA42: ;
		}
	}
	return result;
}

N_NIMCALL(void, log_168216)(ConsoleloggerHEX3Aobjecttype168056* logger, NU8 level, NimStringDesc** args, NI argsLen0) {
	{
		TY168231 LOC5;
		if (!((*logger).Sup.levelthreshold <= level)) goto LA3;
		memset((void*)LOC5, 0, sizeof(LOC5));
		LOC5[0] = substitutelog_168080((*logger).Sup.fmtstr, level, args, argsLen0);
		writeline_168235(stdout, LOC5, 1);
		{
			if (!((48 &(1<<((level)&7)))!=0)) goto LA8;
			fflush(stdout);
		}
		LA8: ;
	}
	LA3: ;
}

N_NIMCALL(void, log_168289)(FileloggerHEX3Aobjecttype168058* logger, NU8 level, NimStringDesc** args, NI argsLen0) {
	{
		TY168231 LOC5;
		if (!((*logger).Sup.levelthreshold <= level)) goto LA3;
		memset((void*)LOC5, 0, sizeof(LOC5));
		LOC5[0] = substitutelog_168080((*logger).Sup.fmtstr, level, args, argsLen0);
		writeline_168235((*logger).file, LOC5, 1);
		{
			if (!((48 &(1<<((level)&7)))!=0)) goto LA8;
			fflush((*logger).file);
		}
		LA8: ;
	}
	LA3: ;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(void, rotate_168523)(RollingfileloggerHEX3Aobjecttype168061* logger) {
	TY122809 LOC1;
	NimStringDesc* dir;
	NimStringDesc* name;
	NimStringDesc* ext;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	nossplitFile((*logger).basename, (&LOC1));
	dir = 0;
	dir = LOC1.Field0;
	name = 0;
	name = LOC1.Field1;
	ext = 0;
	ext = LOC1.Field2;
	{
		NI i_168540;
		NI HEX3Atmp_168543;
		NI res_168546;
		i_168540 = 0;
		HEX3Atmp_168543 = 0;
		HEX3Atmp_168543 = (*logger).logfiles;
		res_168546 = HEX3Atmp_168543;
		{
			while (1) {
				NimStringDesc* srcsuff;
				NimStringDesc* LOC12;
				NimStringDesc* LOC13;
				NimStringDesc* LOC14;
				NimStringDesc* LOC15;
				NimStringDesc* LOC16;
				if (!(((NI) 0) <= res_168546)) goto LA4;
				i_168540 = res_168546;
				{
					NimStringDesc* LOC9;
					NimStringDesc* LOC10;
					if (!!((i_168540 == ((NI) 0)))) goto LA7;
					LOC9 = 0;
					LOC10 = 0;
					LOC10 = nimIntToStr(i_168540);
					LOC9 = rawNewString(LOC10->Sup.len + 1);
appendChar(LOC9, 46);
appendString(LOC9, LOC10);
					srcsuff = LOC9;
				}
				goto LA5;
				LA7: ;
				{
					srcsuff = copyString(((NimStringDesc*) &TMP49));
				}
				LA5: ;
				LOC12 = 0;
				LOC12 = rawNewString(name->Sup.len + ext->Sup.len + srcsuff->Sup.len + 0);
appendString(LOC12, name);
appendString(LOC12, ext);
appendString(LOC12, srcsuff);
				LOC13 = 0;
				LOC13 = HEX2F_122481(dir, LOC12);
				LOC14 = 0;
				LOC15 = 0;
				LOC15 = nimIntToStr((NI)(i_168540 + ((NI) 1)));
				LOC14 = rawNewString(name->Sup.len + ext->Sup.len + LOC15->Sup.len + 1);
appendString(LOC14, name);
appendString(LOC14, ext);
appendChar(LOC14, 46);
appendString(LOC14, LOC15);
				LOC16 = 0;
				LOC16 = HEX2F_122481(dir, LOC14);
				nosmoveFile(LOC13, LOC16);
				res_168546 -= ((NI) 1);
			} LA4: ;
		}
	}
}

N_NIMCALL(void, log_168565)(RollingfileloggerHEX3Aobjecttype168061* logger, NU8 level, NimStringDesc** args, NI argsLen0) {
	{
		TY168231 LOC9;
		if (!((*logger).Sup.Sup.levelthreshold <= level)) goto LA3;
		{
			if (!((*logger).maxlines <= (*logger).curline)) goto LA7;
			fclose((*logger).Sup.file);
			rotate_168523(logger);
			(*logger).logfiles += ((NI) 1);
			(*logger).curline = ((NI) 0);
			(*logger).Sup.file = open_16817((*logger).basename, (*logger).basemode, (*logger).bufsize);
		}
		LA7: ;
		memset((void*)LOC9, 0, sizeof(LOC9));
		LOC9[0] = substitutelog_168080((*logger).Sup.Sup.fmtstr, level, args, argsLen0);
		writeline_168235((*logger).Sup.file, LOC9, 1);
		{
			if (!((48 &(1<<((level)&7)))!=0)) goto LA12;
			fflush((*logger).Sup.file);
		}
		LA12: ;
		(*logger).curline += ((NI) 1);
	}
	LA3: ;
}

N_NIMCALL(void, logloop_168638)(NU8 level, NimStringDesc** args, NI argsLen0) {
	{
		LoggerHEX3Aobjecttype168052* logger_168811;
		NI i_168824;
		NI L_168826;
		logger_168811 = 0;
		i_168824 = ((NI) 0);
		L_168826 = (handlers_168633 ? handlers_168633->Sup.len : 0);
		{
			while (1) {
				if (!(i_168824 < L_168826)) goto LA3;
				logger_168811 = handlers_168633->data[i_168824];
				{
					if (!((*logger_168811).levelthreshold <= level)) goto LA6;
					log_168211(logger_168811, level, args, argsLen0);
				}
				LA6: ;
				i_168824 += ((NI) 1);
			} LA3: ;
		}
	}
}
N_NIMCALL(void, TMP152)(void* p, NI op) {
	LoggerHEX3Aobjecttype168052* a;
	a = (LoggerHEX3Aobjecttype168052*)p;
	nimGCvisit((void*)(*a).fmtstr, op);
}
N_NIMCALL(void, TMP153)(void* p, NI op) {
	TY168632* a;
	NI LOC1;
	a = (TY168632*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, rtladdzct_54204)(Cell48947* c) {
	addzct_52617((&gch_51059.zct), c);
}

static N_INLINE(NIM_BOOL, canbecycleroot_52667)(Cell48947* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(void, rtladdcycleroot_53423)(Cell48947* c) {
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		incl_49665((&gch_51059.cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, decref_54604)(Cell48947* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_54204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_52667(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_53423(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

static N_INLINE(Cell48947*, usrtocell_52646)(void* usr) {
	Cell48947* result;
	result = 0;
	result = ((Cell48947*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell48947))))));
	return result;
}

static N_INLINE(void, nimGCunref)(void* p) {
	Cell48947* LOC1;
	LOC1 = 0;
	LOC1 = usrtocell_52646(p);
	decref_54604(LOC1);
}

static N_INLINE(void, incref_55022)(Cell48947* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_52667(c);
		if (!LOC3) goto LA4;
		rtladdcycleroot_53423(c);
	}
	LA4: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		Cell48947* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_52646(src);
		incref_55022(LOC5);
	}
	LA3: ;
	{
		Cell48947* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_52646((*dest));
		decref_54604(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

N_NIMCALL(void, addhandler_168896)(LoggerHEX3Aobjecttype168052* handler) {
	{
		if (!handlers_168633 == 0) goto LA3;
		if (handlers_168633) nimGCunref(handlers_168633);
		handlers_168633 = (TY168632*) newSeqRC1((&NTI168632), 0);
	}
	LA3: ;
	handlers_168633 = (TY168632*) incrSeqV2(&(handlers_168633)->Sup, sizeof(LoggerHEX3Aobjecttype168052*));
	asgnRef((void**) (&handlers_168633->data[handlers_168633->Sup.len]), handler);
	++handlers_168633->Sup.len;
}
N_NIMCALL(void, TMP158)(void* p, NI op) {
	RollingfileloggerHEX3Aobjecttype168061* a;
	a = (RollingfileloggerHEX3Aobjecttype168061*)p;
	nimGCvisit((void*)(*a).Sup.Sup.fmtstr, op);
	nimGCvisit((void*)(*a).basename, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell48947* c;
	c = usrtocell_52646(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_54204(c);
	}
	LA3: ;
}

static N_INLINE(NIM_BOOL, direxists_126020)(NimStringDesc* dir) {
	NIM_BOOL result;
	result = 0;
	result = nosexistsDir(dir);
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_90363)(NimStringDesc* s, Slice90370 x) {
	NimStringDesc* result;
	result = 0;
	result = copyStrLast(s, x.a, x.b);
	return result;
}

static N_INLINE(Slice90370, HEX2EHEX2E_104291)(NI a, NI b) {
	Slice90370 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = 0;
	result = currexception_20845;
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_20845), NIM_NIL);
}

N_NIMCALL(NI, countfiles_168421)(NimStringDesc* filename) {
	NI volatile result;
	TY122809 LOC1;
	NimStringDesc* dir;
	NimStringDesc* name;
	NimStringDesc* ext;
	result = 0;
	result = ((NI) 0);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	nossplitFile(filename, (&LOC1));
	dir = 0;
	dir = LOC1.Field0;
	name = 0;
	name = LOC1.Field1;
	ext = 0;
	ext = LOC1.Field2;
	{
		NU8 kind_168428;
		NimStringDesc* path_168429;
		DIR* d_168457;
		kind_168428 = 0;
		path_168429 = 0;
		d_168457 = opendir(dir->data);
		{
			int LOC99;
			if (!!((d_168457 == NIM_NIL))) goto LA5;
			{
				while (1) {
					{
						struct dirent* x_168459;
						NimStringDesc* y_168461;
						x_168459 = readdir(d_168457);
						{
							if (!(x_168459 == NIM_NIL)) goto LA12;
							goto LA7;
						}
						LA12: ;
						y_168461 = cstrToNimstr(((NCSTRING) ((*x_168459).d_name)));
						{
							NIM_BOOL LOC16;
							struct stat s_168463;
							NU8 k_168465;
							LOC16 = 0;
							LOC16 = !(eqStrings(y_168461, ((NimStringDesc*) &TMP159)));
							if (!(LOC16)) goto LA17;
							LOC16 = !(eqStrings(y_168461, ((NimStringDesc*) &TMP160)));
							LA17: ;
							if (!LOC16) goto LA18;
							memset((void*)(&s_168463), 0, sizeof(s_168463));
							{
								if (!NIM_TRUE) goto LA22;
								y_168461 = HEX2F_122481(dir, y_168461);
							}
							LA22: ;
							k_168465 = ((NU8) 0);
							{
								if (!!(((*x_168459).d_type == ((NI8) 0)))) goto LA26;
								{
									if (!((*x_168459).d_type == ((NI8) 4))) goto LA30;
									k_168465 = ((NU8) 2);
								}
								LA30: ;
								{
									if (!((*x_168459).d_type == ((NI8) 10))) goto LA34;
									{
										NIM_BOOL LOC38;
										LOC38 = 0;
										LOC38 = direxists_126020(y_168461);
										if (!LOC38) goto LA39;
										k_168465 = ((NU8) 3);
									}
									goto LA36;
									LA39: ;
									{
										k_168465 = (NU8)(k_168465 + ((NI) 1));
									}
									LA36: ;
								}
								LA34: ;
								kind_168428 = k_168465;
								path_168429 = y_168461;
								{
									NimStringDesc* llfn;
									NimStringDesc* LOC46;
									if (!(kind_168428 == ((NU8) 0))) goto LA44;
									LOC46 = 0;
									LOC46 = rawNewString(name->Sup.len + ext->Sup.len + 1);
appendString(LOC46, name);
appendString(LOC46, ext);
appendChar(LOC46, 46);
									llfn = LOC46;
									{
										NimStringDesc* LOC49;
										NIM_BOOL LOC50;
										NimStringDesc* nums;
										NimStringDesc* LOC53;
										NimStringDesc* LOC54;
										Slice90370 LOC55;
										TSafePoint TMP161;
										LOC49 = 0;
										LOC49 = nosextractFilename(path_168429);
										LOC50 = 0;
										LOC50 = nsuStartsWith(LOC49, llfn);
										if (!LOC50) goto LA51;
										LOC53 = 0;
										LOC53 = nosextractFilename(path_168429);
										LOC54 = 0;
										LOC54 = nosextractFilename(path_168429);
										LOC55 = HEX2EHEX2E_104291((llfn ? llfn->Sup.len : 0), (NI)((LOC54 ? LOC54->Sup.len : 0) - ((NI) 1)));
										nums = HEX5BHEX5D_90363(LOC53, LOC55);
										pushSafePoint(&TMP161);
										TMP161.status = setjmp(TMP161.context);
										if (TMP161.status == 0) {
											NI num;
											num = nsuParseInt(nums);
											{
												if (!(result < num)) goto LA59;
												result = num;
											}
											LA59: ;
											popSafePoint();
										}
										else {
											popSafePoint();
											if (isObj(getCurrentException()->Sup.m_type, (&NTI4049))) {
												TMP161.status = 0;
												popCurrentException();
											}
										}
										if (TMP161.status != 0) reraiseException();
									}
									LA51: ;
								}
								LA44: ;
								goto LA9;
							}
							LA26: ;
							{
								int LOC65;
								LOC65 = 0;
								LOC65 = lstat(y_168461->data, (&s_168463));
								if (!(LOC65 < ((NI32) 0))) goto LA66;
								goto LA7;
							}
							LA66: ;
							{
								NIM_BOOL LOC70;
								LOC70 = 0;
								LOC70 = S_ISDIR(s_168463.st_mode);
								if (!LOC70) goto LA71;
								k_168465 = ((NU8) 2);
							}
							LA71: ;
							{
								NIM_BOOL LOC75;
								LOC75 = 0;
								LOC75 = S_ISLNK(s_168463.st_mode);
								if (!LOC75) goto LA76;
								k_168465 = (NU8)(k_168465 + ((NI) 1));
							}
							LA76: ;
							kind_168428 = k_168465;
							path_168429 = y_168461;
							{
								NimStringDesc* llfn_168467;
								NimStringDesc* LOC82;
								if (!(kind_168428 == ((NU8) 0))) goto LA80;
								LOC82 = 0;
								LOC82 = rawNewString(name->Sup.len + ext->Sup.len + 1);
appendString(LOC82, name);
appendString(LOC82, ext);
appendChar(LOC82, 46);
								llfn_168467 = LOC82;
								{
									NimStringDesc* LOC85;
									NIM_BOOL LOC86;
									NimStringDesc* nums_168469;
									NimStringDesc* LOC89;
									NimStringDesc* LOC90;
									Slice90370 LOC91;
									TSafePoint TMP162;
									LOC85 = 0;
									LOC85 = nosextractFilename(path_168429);
									LOC86 = 0;
									LOC86 = nsuStartsWith(LOC85, llfn_168467);
									if (!LOC86) goto LA87;
									LOC89 = 0;
									LOC89 = nosextractFilename(path_168429);
									LOC90 = 0;
									LOC90 = nosextractFilename(path_168429);
									LOC91 = HEX2EHEX2E_104291((llfn_168467 ? llfn_168467->Sup.len : 0), (NI)((LOC90 ? LOC90->Sup.len : 0) - ((NI) 1)));
									nums_168469 = HEX5BHEX5D_90363(LOC89, LOC91);
									pushSafePoint(&TMP162);
									TMP162.status = setjmp(TMP162.context);
									if (TMP162.status == 0) {
										NI num_168471;
										num_168471 = nsuParseInt(nums_168469);
										{
											if (!(result < num_168471)) goto LA95;
											result = num_168471;
										}
										LA95: ;
										popSafePoint();
									}
									else {
										popSafePoint();
										if (isObj(getCurrentException()->Sup.m_type, (&NTI4049))) {
											TMP162.status = 0;
											popCurrentException();
										}
									}
									if (TMP162.status != 0) reraiseException();
								}
								LA87: ;
							}
							LA80: ;
						}
						LA18: ;
					} LA9: ;
				}
			} LA7: ;
			LOC99 = 0;
			LOC99 = closedir(d_168457);
		}
		LA5: ;
	}
	return result;
}

N_NIMCALL(NI, countloglines_168386)(RollingfileloggerHEX3Aobjecttype168061* logger) {
	NI result;
	result = 0;
	result = ((NI) 0);
	{
		NimStringDesc* line_168390;
		FILE* HEX3Atmp_168401;
		NimStringDesc* res_168404;
		line_168390 = 0;
		HEX3Atmp_168401 = 0;
		HEX3Atmp_168401 = (*logger).Sup.file;
		res_168404 = rawNewString(((NI) 80));
		{
			while (1) {
				NIM_BOOL LOC4;
				LOC4 = 0;
				LOC4 = readline_16919(HEX3Atmp_168401, (&res_168404));
				if (!LOC4) goto LA3;
				line_168390 = res_168404;
				result += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(RollingfileloggerHEX3Aobjecttype168061*, newrollingfilelogger_168490)(NimStringDesc* filename, NU8 mode, NU8 levelthreshold, NimStringDesc* fmtstr, NI maxlines, NI bufsize) {
	RollingfileloggerHEX3Aobjecttype168061* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	result = 0;
	result = (RollingfileloggerHEX3Aobjecttype168061*) newObj((&NTI168051), sizeof(RollingfileloggerHEX3Aobjecttype168061));
	(*result).Sup.Sup.Sup.m_type = (&NTI168061);
	(*result).Sup.Sup.levelthreshold = levelthreshold;
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.fmtstr; (*result).Sup.Sup.fmtstr = copyStringRC1(fmtstr);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	(*result).maxlines = maxlines;
	(*result).bufsize = bufsize;
	(*result).Sup.file = open_16817(filename, mode, (*result).bufsize);
	(*result).curline = ((NI) 0);
	LOC2 = 0;
	LOC2 = (*result).basename; (*result).basename = copyStringRC1(filename);
	if (LOC2) nimGCunrefNoCycle(LOC2);
	(*result).basemode = mode;
	(*result).logfiles = countfiles_168421(filename);
	{
		if (!(mode == ((NU8) 4))) goto LA5;
		(*result).curline = countloglines_168386(result);
	}
	LA5: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_loggingInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_loggingDatInit000)(void) {
static TNimNode* TMP148[2];
static TNimNode* TMP149[7];
NI TMP151;
static char* NIM_CONST TMP150[7] = {
"lvlAll", 
"lvlDebug", 
"lvlInfo", 
"lvlWarn", 
"lvlError", 
"lvlFatal", 
"lvlNone"};
static TNimNode* TMP154[6];
static TNimNode TMP41[20];
NTI168052.size = sizeof(LoggerHEX3Aobjecttype168052);
NTI168052.kind = 17;
NTI168052.base = (&NTI4011);
TMP148[0] = &TMP41[1];
NTI168022.size = sizeof(NU8);
NTI168022.kind = 14;
NTI168022.base = 0;
NTI168022.flags = 3;
for (TMP151 = 0; TMP151 < 7; TMP151++) {
TMP41[TMP151+2].kind = 1;
TMP41[TMP151+2].offset = TMP151;
TMP41[TMP151+2].name = TMP150[TMP151];
TMP149[TMP151] = &TMP41[TMP151+2];
}
TMP41[9].len = 7; TMP41[9].kind = 2; TMP41[9].sons = &TMP149[0];
NTI168022.node = &TMP41[9];
TMP41[1].kind = 1;
TMP41[1].offset = offsetof(LoggerHEX3Aobjecttype168052, levelthreshold);
TMP41[1].typ = (&NTI168022);
TMP41[1].name = "levelThreshold";
TMP148[1] = &TMP41[10];
TMP41[10].kind = 1;
TMP41[10].offset = offsetof(LoggerHEX3Aobjecttype168052, fmtstr);
TMP41[10].typ = (&NTI149);
TMP41[10].name = "fmtStr";
TMP41[0].len = 2; TMP41[0].kind = 2; TMP41[0].sons = &TMP148[0];
NTI168052.node = &TMP41[0];
NTI168045.size = sizeof(LoggerHEX3Aobjecttype168052*);
NTI168045.kind = 22;
NTI168045.base = (&NTI168052);
NTI168045.marker = TMP152;
NTI168632.size = sizeof(TY168632*);
NTI168632.kind = 24;
NTI168632.base = (&NTI168045);
NTI168632.marker = TMP153;
NTI168058.size = sizeof(FileloggerHEX3Aobjecttype168058);
NTI168058.kind = 17;
NTI168058.base = (&NTI168052);
TMP41[11].kind = 1;
TMP41[11].offset = offsetof(FileloggerHEX3Aobjecttype168058, file);
TMP41[11].typ = (&NTI16404);
TMP41[11].name = "file";
NTI168058.node = &TMP41[11];
NTI168061.size = sizeof(RollingfileloggerHEX3Aobjecttype168061);
NTI168061.kind = 17;
NTI168061.base = (&NTI168058);
TMP154[0] = &TMP41[13];
TMP41[13].kind = 1;
TMP41[13].offset = offsetof(RollingfileloggerHEX3Aobjecttype168061, maxlines);
TMP41[13].typ = (&NTI108);
TMP41[13].name = "maxLines";
TMP154[1] = &TMP41[14];
TMP41[14].kind = 1;
TMP41[14].offset = offsetof(RollingfileloggerHEX3Aobjecttype168061, curline);
TMP41[14].typ = (&NTI108);
TMP41[14].name = "curLine";
TMP154[2] = &TMP41[15];
TMP41[15].kind = 1;
TMP41[15].offset = offsetof(RollingfileloggerHEX3Aobjecttype168061, basename);
TMP41[15].typ = (&NTI149);
TMP41[15].name = "baseName";
TMP154[3] = &TMP41[16];
TMP41[16].kind = 1;
TMP41[16].offset = offsetof(RollingfileloggerHEX3Aobjecttype168061, basemode);
TMP41[16].typ = (&NTI16406);
TMP41[16].name = "baseMode";
TMP154[4] = &TMP41[17];
TMP41[17].kind = 1;
TMP41[17].offset = offsetof(RollingfileloggerHEX3Aobjecttype168061, logfiles);
TMP41[17].typ = (&NTI108);
TMP41[17].name = "logFiles";
TMP154[5] = &TMP41[18];
TMP41[18].kind = 1;
TMP41[18].offset = offsetof(RollingfileloggerHEX3Aobjecttype168061, bufsize);
TMP41[18].typ = (&NTI108);
TMP41[18].name = "bufSize";
TMP41[12].len = 6; TMP41[12].kind = 2; TMP41[12].sons = &TMP154[0];
NTI168061.node = &TMP41[12];
NTI168051.size = sizeof(RollingfileloggerHEX3Aobjecttype168061*);
NTI168051.kind = 22;
NTI168051.base = (&NTI168061);
NTI168051.marker = TMP158;
NTI168056.size = sizeof(ConsoleloggerHEX3Aobjecttype168056);
NTI168056.kind = 17;
NTI168056.base = (&NTI168052);
TMP41[19].len = 0; TMP41[19].kind = 2;
NTI168056.node = &TMP41[19];
}

