/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/monitor_ambient_light.o /home/sensey/Projects/nim-test/nimcache/monitor_ambient_light.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Configambientlight170049 Configambientlight170049;
typedef struct Filestreamobj141467 Filestreamobj141467;
typedef struct Cfgparser166214 Cfgparser166214;
typedef struct Baselexer162032 Baselexer162032;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Streamobj140227 Streamobj140227;
typedef struct Token166212 Token166212;
typedef struct Configentity170005 Configentity170005;
typedef struct Cfgevent166208 Cfgevent166208;
typedef struct LoggerHEX3Aobjecttype168052 LoggerHEX3Aobjecttype168052;
typedef struct RollingfileloggerHEX3Aobjecttype168061 RollingfileloggerHEX3Aobjecttype168061;
typedef struct Commandstarter161005 Commandstarter161005;
typedef struct Sensorfinder143137 Sensorfinder143137;
typedef struct Normalizer144007 Normalizer144007;
typedef struct Sensorambientlight143032 Sensorambientlight143032;
typedef struct FileloggerHEX3Aobjecttype168058 FileloggerHEX3Aobjecttype168058;
typedef struct ConsoleloggerHEX3Aobjecttype168056 ConsoleloggerHEX3Aobjecttype168056;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Configambientlight170049  {
NimStringDesc* path;
NI timeout;
NI threshold;
NI intensitymin;
NI intensitymax;
NI backlightmin;
NI backlightmax;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef NU8 TY162040[32];
struct  Baselexer162032  {
  TNimObject Sup;
NI bufpos;
NCSTRING buf;
NI buflen;
Streamobj140227* input;
NI linenumber;
NI sentinel;
NI linestart;
TY162040 refillchars;
};
struct  Token166212  {
NU8 kind;
NimStringDesc* literal;
};
struct  Cfgparser166214  {
  Baselexer162032 Sup;
Token166212 tok;
NimStringDesc* filename;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Configentity170005  {
NimStringDesc* name;
NimStringDesc* value;
NimStringDesc* section;
};
struct  Cfgevent166208  {
  TNimObject Sup;
NU8 kind;
union{
struct {NimStringDesc* section;
} S2;
struct {NimStringDesc* key;
NimStringDesc* value;
} S3;
struct {NimStringDesc* msg;
} S4;
} kindU;
};
typedef NimStringDesc* TY168231[1];
struct  Commandstarter161005  {
NimStringDesc* path;
};
struct  Sensorfinder143137  {
NimStringDesc* path;
};
struct  Normalizer144007  {
NI max;
NI min;
};
struct  Sensorambientlight143032  {
NimStringDesc* path;
NimStringDesc* prefixname;
NimStringDesc* prefixelement;
NimStringDesc* prefixintensity;
};
typedef NIM_CHAR TY112386[256];
typedef N_NOCONV_PTR(void, TY20205) (void);
typedef NimStringDesc* TY172717[2];
typedef N_NIMCALL_PTR(void, TY140228) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY140232) (Streamobj140227* s);
typedef N_NIMCALL_PTR(void, TY140236) (Streamobj140227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY140241) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NI, TY140245) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY140251) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140257) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140263) (Streamobj140227* s);
struct  Streamobj140227  {
  TNimObject Sup;
TY140228 closeimpl;
TY140232 atendimpl;
TY140236 setpositionimpl;
TY140241 getpositionimpl;
TY140245 readdataimpl;
TY140251 peekdataimpl;
TY140257 writedataimpl;
TY140263 flushimpl;
};
struct  Filestreamobj141467  {
  Streamobj140227 Sup;
FILE* f;
};
struct  LoggerHEX3Aobjecttype168052  {
  TNimObject Sup;
NU8 levelthreshold;
NimStringDesc* fmtstr;
};
struct  FileloggerHEX3Aobjecttype168058  {
  LoggerHEX3Aobjecttype168052 Sup;
FILE* file;
};
struct  RollingfileloggerHEX3Aobjecttype168061  {
  FileloggerHEX3Aobjecttype168058 Sup;
NI maxlines;
NI curline;
NimStringDesc* basename;
NU8 basemode;
NI logfiles;
NI bufsize;
};
struct  ConsoleloggerHEX3Aobjecttype168056  {
  LoggerHEX3Aobjecttype168052 Sup;
};
N_NIMCALL(void, main_172004)(NimStringDesc* file, NimStringDesc* log);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
static N_INLINE(NimStringDesc*, get_170060)(Configambientlight170049* this_170063, NimStringDesc* section, NimStringDesc* name);
N_NIMCALL(Filestreamobj141467*, newfilestream_141559)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(void, npcopen)(Cfgparser166214* c, Streamobj140227* input, NimStringDesc* filename, NI lineoffset);
N_NIMCALL(void, npcnext)(Cfgparser166214* c, Cfgevent166208* Result);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, logloop_168638)(NU8 level, NimStringDesc** args, NI argsLen0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, npcclose)(Cfgparser166214* c);
N_NIMCALL(void, addhandler_168896)(LoggerHEX3Aobjecttype168052* handler);
N_NIMCALL(RollingfileloggerHEX3Aobjecttype168061*, newrollingfilelogger_168490)(NimStringDesc* filename, NU8 mode, NU8 levelthreshold, NimStringDesc* fmtstr, NI maxlines, NI bufsize);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
static N_INLINE(void, get_143234)(Sensorfinder143137* this_143237, NimStringDesc* name, Sensorambientlight143032* Result);
static N_INLINE(NimStringDesc*, device_143181)(Sensorfinder143137* this_143184, NimStringDesc* name);
static N_INLINE(NIM_BOOL, direxists_126020)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, HEX2F_122481)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, getfilecontents_143007)(NimStringDesc* source);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NIM_BOOL, exists_143040)(Sensorambientlight143032* this_143043);
static N_INLINE(NIM_BOOL, enable_143095)(Sensorambientlight143032* this_143098);
N_NIMCALL(NIM_BOOL, parsebool_101305)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, setfilecontents_143019)(NimStringDesc* source, NimStringDesc* value);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, nossleep)(NI milsecs);
N_NIMCALL(void, setcontrolchook_20201)(TY20205 hook);
N_NOCONV(void, handler_171012)(void);
static N_INLINE(NI, percent_144013)(Normalizer144007* this_144016, NI raw);
static N_INLINE(NF, HEX2F_90317)(NI x, NI y);
static N_INLINE(NI, intensity_143081)(Sensorambientlight143032* this_143084);
N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command);
N_NIMCALL(void, log_168565)(RollingfileloggerHEX3Aobjecttype168061* logger, NU8 level, NimStringDesc** args, NI argsLen0);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NOINLINE(NIM_BOOL, isobjslowpath_25161)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(void, log_168289)(FileloggerHEX3Aobjecttype168058* logger, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, log_168216)(ConsoleloggerHEX3Aobjecttype168056* logger, NU8 level, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, log_168201)(LoggerHEX3Aobjecttype168052* logger, NU8 level, NimStringDesc** args, NI argsLen0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sensorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sensorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_normalizerInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_normalizerDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_starterInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_starterDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parsecfgInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parsecfgDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_loggingInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_loggingDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_configInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_configDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_signalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_signalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, monitor_ambient_lightInit000)(void);
NIM_EXTERNC N_NOINLINE(void, monitor_ambient_lightDatInit000)(void);
STRING_LITERAL(TMP137, "command: ", 9);
STRING_LITERAL(TMP138, ": ", 2);
STRING_LITERAL(TMP139, "als", 3);
STRING_LITERAL(TMP140, "timeout", 7);
STRING_LITERAL(TMP141, "intensity_min", 13);
STRING_LITERAL(TMP142, "intensity_max", 13);
STRING_LITERAL(TMP143, "intensity_threshold", 19);
STRING_LITERAL(TMP144, "backlight_min", 13);
STRING_LITERAL(TMP145, "backlight_max", 13);
STRING_LITERAL(TMP146, "location_sensor", 15);
STRING_LITERAL(TMP147, "location_script", 15);
STRING_LITERAL(TMP163, "$levelname ", 11);
STRING_LITERAL(TMP164, "intensity minimal: $#", 21);
STRING_LITERAL(TMP165, "intensity maximal: $#", 21);
STRING_LITERAL(TMP166, "intensity threshold: $#", 23);
STRING_LITERAL(TMP167, "backlight minimal: $#", 21);
STRING_LITERAL(TMP168, "backlight maximal: $#", 21);
STRING_LITERAL(TMP169, "sensors:\011$#", 11);
STRING_LITERAL(TMP170, "scripts:\011$#", 11);
STRING_LITERAL(TMP171, ".", 1);
STRING_LITERAL(TMP172, "..", 2);
STRING_LITERAL(TMP173, "iio:device", 10);
STRING_LITERAL(TMP174, "/name", 5);
STRING_LITERAL(TMP176, "/scan_elements", 14);
STRING_LITERAL(TMP177, "/in_intensity_both_raw", 22);
STRING_LITERAL(TMP178, "_en", 3);
STRING_LITERAL(TMP190, "1", 1);
STRING_LITERAL(TMP191, "sensor not found, sleep: $# ", 28);
STRING_LITERAL(TMP194, "ambient light: $#, backlight: $#", 32);
STRING_LITERAL(TMP195, "$# $#", 5);
STRING_LITERAL(TMP196, "starter script error number: $# ", 32);
STRING_LITERAL(TMP197, "/etc/monitor-ambient-light/monitor-ambient-light.ini", 52);
STRING_LITERAL(TMP198, "/var/log/monitor-ambient-light.log", 34);
extern TNimType NTI166214; /* CfgParser */
extern TNimType NTI166208; /* CfgEvent */
extern NU8 level_168627;
extern TNimType NTI168061; /* RollingFileLogger:ObjectType */
extern TNimType NTI168058; /* FileLogger:ObjectType */
static TNimType* Nim_OfCheck_CACHE1[2];
extern TNimType NTI168056; /* ConsoleLogger:ObjectType */
extern TNimType NTI168052; /* Logger:ObjectType */
static TNimType* Nim_OfCheck_CACHE2[2];

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NimStringDesc*, get_170060)(Configambientlight170049* this_170063, NimStringDesc* section, NimStringDesc* name) {
	NimStringDesc* result;
	Filestreamobj141467* stream;
	Cfgparser166214 parser;
	Cfgparser166214 LOC1;
	Streamobj140227* LOC2;
	Configentity170005 entity;
	Configentity170005 LOC3;
{	result = 0;
	stream = newfilestream_141559((*this_170063).path, ((NU8) 0));
	memset((void*)(&parser), 0, sizeof(parser));
	parser.Sup.Sup.m_type = (&NTI166214);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.Sup.m_type = (&NTI166214);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.Sup.m_type = (&NTI166214);
	memcpy((void*)(&parser), (NIM_CONST void*)(&LOC1), sizeof(parser));
	LOC2 = 0;
	LOC2 = &stream->Sup;
	npcopen((&parser), LOC2, (*this_170063).path, ((NI) 0));
	memset((void*)(&entity), 0, sizeof(entity));
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	entity.name = LOC3.name;
	entity.value = LOC3.value;
	entity.section = LOC3.section;
	{
		while (1) {
			Cfgevent166208 expression;
			memset((void*)(&expression), 0, sizeof(expression));
			expression.Sup.m_type = (&NTI166208);
			chckNil((void*)(&expression));
			memset((void*)(&expression), 0, sizeof(expression));
			expression.Sup.m_type = (&NTI166208);
			npcnext((&parser), (&expression));
			switch (expression.kind) {
			case ((NU8) 0):
			{
				goto LA4;
			}
			break;
			case ((NU8) 1):
			{
				{
					if (!eqStrings(expression.kindU.S2.section, section)) goto LA10;
					entity.section = copyString(section);
				}
				LA10: ;
			}
			break;
			case ((NU8) 2):
			{
				entity.name = copyString(expression.kindU.S3.key);
				entity.value = copyString(expression.kindU.S3.value);
				{
					if (!eqStrings(entity.section, section)) goto LA15;
					{
						if (!eqStrings(entity.name, name)) goto LA19;
						result = copyString(entity.value);
						goto BeforeRet;
					}
					LA19: ;
				}
				LA15: ;
			}
			break;
			case ((NU8) 3):
			{
				{
					TY168231 LOC26;
					NimStringDesc* LOC27;
					if (!(level_168627 <= ((NU8) 1))) goto LA24;
					memset((void*)LOC26, 0, sizeof(LOC26));
					LOC27 = 0;
					LOC27 = rawNewString(expression.kindU.S3.key->Sup.len + expression.kindU.S3.value->Sup.len + 11);
appendString(LOC27, ((NimStringDesc*) &TMP137));
appendString(LOC27, expression.kindU.S3.key);
appendString(LOC27, ((NimStringDesc*) &TMP138));
appendString(LOC27, expression.kindU.S3.value);
					LOC26[0] = LOC27;
					logloop_168638(((NU8) 1), LOC26, 1);
				}
				LA24: ;
			}
			break;
			case ((NU8) 4):
			{
				{
					TY168231 LOC33;
					if (!(level_168627 <= ((NU8) 4))) goto LA31;
					memset((void*)LOC33, 0, sizeof(LOC33));
					LOC33[0] = copyString(expression.kindU.S4.msg);
					logloop_168638(((NU8) 4), LOC33, 1);
				}
				LA31: ;
			}
			break;
			}
		}
	} LA4: ;
	npcclose((&parser));
	result = copyString(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, direxists_126020)(NimStringDesc* dir) {
	NIM_BOOL result;
	result = 0;
	result = nosexistsDir(dir);
	return result;
}

static N_INLINE(NimStringDesc*, device_143181)(Sensorfinder143137* this_143184, NimStringDesc* name) {
	NimStringDesc* result;
{	result = 0;
	{
		NimStringDesc* path_143187;
		path_143187 = 0;
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = direxists_126020((*this_143184).path);
			if (!LOC4) goto LA5;
			{
				NU8 kind_143196;
				NimStringDesc* path_143198;
				NimStringDesc* HEX3Atmp_143200;
				DIR* d_143202;
				kind_143196 = 0;
				path_143198 = 0;
				HEX3Atmp_143200 = 0;
				HEX3Atmp_143200 = (*this_143184).path;
				d_143202 = opendir(HEX3Atmp_143200->data);
				{
					int LOC92;
					if (!!((d_143202 == NIM_NIL))) goto LA10;
					{
						while (1) {
							{
								struct dirent* x_143204;
								NimStringDesc* y_143206;
								x_143204 = readdir(d_143202);
								{
									if (!(x_143204 == NIM_NIL)) goto LA17;
									goto LA12;
								}
								LA17: ;
								y_143206 = cstrToNimstr(((NCSTRING) ((*x_143204).d_name)));
								{
									NIM_BOOL LOC21;
									struct stat s_143208;
									NU8 k_143210;
									LOC21 = 0;
									LOC21 = !(eqStrings(y_143206, ((NimStringDesc*) &TMP171)));
									if (!(LOC21)) goto LA22;
									LOC21 = !(eqStrings(y_143206, ((NimStringDesc*) &TMP172)));
									LA22: ;
									if (!LOC21) goto LA23;
									memset((void*)(&s_143208), 0, sizeof(s_143208));
									{
										if (!NIM_TRUE) goto LA27;
										y_143206 = HEX2F_122481(HEX3Atmp_143200, y_143206);
									}
									LA27: ;
									k_143210 = ((NU8) 0);
									{
										if (!!(((*x_143204).d_type == ((NI8) 0)))) goto LA31;
										{
											if (!((*x_143204).d_type == ((NI8) 4))) goto LA35;
											k_143210 = ((NU8) 2);
										}
										LA35: ;
										{
											if (!((*x_143204).d_type == ((NI8) 10))) goto LA39;
											{
												NIM_BOOL LOC43;
												LOC43 = 0;
												LOC43 = direxists_126020(y_143206);
												if (!LOC43) goto LA44;
												k_143210 = ((NU8) 3);
											}
											goto LA41;
											LA44: ;
											{
												k_143210 = (NU8)(k_143210 + ((NI) 1));
											}
											LA41: ;
										}
										LA39: ;
										kind_143196 = k_143210;
										path_143198 = y_143206;
										{
											NI LOC49;
											NimStringDesc* source;
											LOC49 = 0;
											LOC49 = nsuFindStr(path_143198, ((NimStringDesc*) &TMP173), ((NI) 0));
											if (!!((LOC49 == ((NI) -1)))) goto LA50;
											path_143187 = path_143198;
											source = nosjoinPath(path_143187, ((NimStringDesc*) &TMP174));
											{
												NIM_BOOL LOC54;
												LOC54 = 0;
												LOC54 = nosexistsFile(source);
												if (!LOC54) goto LA55;
												{
													NimStringDesc* LOC59;
													LOC59 = 0;
													LOC59 = getfilecontents_143007(source);
													if (!eqStrings(LOC59, name)) goto LA60;
													result = copyString(path_143187);
													goto BeforeRet;
												}
												LA60: ;
											}
											LA55: ;
										}
										LA50: ;
										goto LA14;
									}
									LA31: ;
									{
										int LOC64;
										LOC64 = 0;
										LOC64 = lstat(y_143206->data, (&s_143208));
										if (!(LOC64 < ((NI32) 0))) goto LA65;
										goto LA12;
									}
									LA65: ;
									{
										NIM_BOOL LOC69;
										LOC69 = 0;
										LOC69 = S_ISDIR(s_143208.st_mode);
										if (!LOC69) goto LA70;
										k_143210 = ((NU8) 2);
									}
									LA70: ;
									{
										NIM_BOOL LOC74;
										LOC74 = 0;
										LOC74 = S_ISLNK(s_143208.st_mode);
										if (!LOC74) goto LA75;
										k_143210 = (NU8)(k_143210 + ((NI) 1));
									}
									LA75: ;
									kind_143196 = k_143210;
									path_143198 = y_143206;
									{
										NI LOC79;
										NimStringDesc* source_143212;
										LOC79 = 0;
										LOC79 = nsuFindStr(path_143198, ((NimStringDesc*) &TMP173), ((NI) 0));
										if (!!((LOC79 == ((NI) -1)))) goto LA80;
										path_143187 = path_143198;
										source_143212 = nosjoinPath(path_143187, ((NimStringDesc*) &TMP174));
										{
											NIM_BOOL LOC84;
											LOC84 = 0;
											LOC84 = nosexistsFile(source_143212);
											if (!LOC84) goto LA85;
											{
												NimStringDesc* LOC89;
												LOC89 = 0;
												LOC89 = getfilecontents_143007(source_143212);
												if (!eqStrings(LOC89, name)) goto LA90;
												result = copyString(path_143187);
												goto BeforeRet;
											}
											LA90: ;
										}
										LA85: ;
									}
									LA80: ;
								}
								LA23: ;
							} LA14: ;
						}
					} LA12: ;
					LOC92 = 0;
					LOC92 = closedir(d_143202);
				}
				LA10: ;
			}
		}
		LA5: ;
	}
	result = copyString(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, get_143234)(Sensorfinder143137* this_143237, NimStringDesc* name, Sensorambientlight143032* Result) {
	NimStringDesc* sensorpath;
	Sensorambientlight143032 LOC1;
{	sensorpath = device_143181(this_143237, name);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.path = copyString(sensorpath);
	LOC1.prefixname = copyString(((NimStringDesc*) &TMP174));
	LOC1.prefixelement = copyString(((NimStringDesc*) &TMP176));
	LOC1.prefixintensity = copyString(((NimStringDesc*) &TMP177));
	unsureAsgnRef((void**) (&(*Result).path), LOC1.path);
	unsureAsgnRef((void**) (&(*Result).prefixname), LOC1.prefixname);
	unsureAsgnRef((void**) (&(*Result).prefixelement), LOC1.prefixelement);
	unsureAsgnRef((void**) (&(*Result).prefixintensity), LOC1.prefixintensity);
	goto BeforeRet;
	}BeforeRet: ;
}

static N_INLINE(NIM_BOOL, exists_143040)(Sensorambientlight143032* this_143043) {
	NIM_BOOL result;
	NimStringDesc* source;
{	result = 0;
	source = nosjoinPath((*this_143043).path, (*this_143043).prefixelement);
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nosexistsDir(source);
		if (!LOC3) goto LA4;
		{
			NU8 kind_143048;
			NimStringDesc* pathelement_143049;
			DIR* d_143054;
			kind_143048 = 0;
			pathelement_143049 = 0;
			d_143054 = opendir(source->data);
			{
				int LOC61;
				if (!!((d_143054 == NIM_NIL))) goto LA9;
				{
					while (1) {
						{
							struct dirent* x_143056;
							NimStringDesc* y_143058;
							x_143056 = readdir(d_143054);
							{
								if (!(x_143056 == NIM_NIL)) goto LA16;
								goto LA11;
							}
							LA16: ;
							y_143058 = cstrToNimstr(((NCSTRING) ((*x_143056).d_name)));
							{
								NIM_BOOL LOC20;
								struct stat s_143060;
								NU8 k_143062;
								LOC20 = 0;
								LOC20 = !(eqStrings(y_143058, ((NimStringDesc*) &TMP171)));
								if (!(LOC20)) goto LA21;
								LOC20 = !(eqStrings(y_143058, ((NimStringDesc*) &TMP172)));
								LA21: ;
								if (!LOC20) goto LA22;
								memset((void*)(&s_143060), 0, sizeof(s_143060));
								{
									if (!NIM_TRUE) goto LA26;
									y_143058 = HEX2F_122481(source, y_143058);
								}
								LA26: ;
								k_143062 = ((NU8) 0);
								{
									if (!!(((*x_143056).d_type == ((NI8) 0)))) goto LA30;
									{
										if (!((*x_143056).d_type == ((NI8) 4))) goto LA34;
										k_143062 = ((NU8) 2);
									}
									LA34: ;
									{
										if (!((*x_143056).d_type == ((NI8) 10))) goto LA38;
										{
											NIM_BOOL LOC42;
											LOC42 = 0;
											LOC42 = direxists_126020(y_143058);
											if (!LOC42) goto LA43;
											k_143062 = ((NU8) 3);
										}
										goto LA40;
										LA43: ;
										{
											k_143062 = (NU8)(k_143062 + ((NI) 1));
										}
										LA40: ;
									}
									LA38: ;
									kind_143048 = k_143062;
									pathelement_143049 = y_143058;
									result = nosexistsFile(pathelement_143049);
									goto BeforeRet;
									goto LA13;
								}
								LA30: ;
								{
									int LOC48;
									LOC48 = 0;
									LOC48 = lstat(y_143058->data, (&s_143060));
									if (!(LOC48 < ((NI32) 0))) goto LA49;
									goto LA11;
								}
								LA49: ;
								{
									NIM_BOOL LOC53;
									LOC53 = 0;
									LOC53 = S_ISDIR(s_143060.st_mode);
									if (!LOC53) goto LA54;
									k_143062 = ((NU8) 2);
								}
								LA54: ;
								{
									NIM_BOOL LOC58;
									LOC58 = 0;
									LOC58 = S_ISLNK(s_143060.st_mode);
									if (!LOC58) goto LA59;
									k_143062 = (NU8)(k_143062 + ((NI) 1));
								}
								LA59: ;
								kind_143048 = k_143062;
								pathelement_143049 = y_143058;
								result = nosexistsFile(pathelement_143049);
								goto BeforeRet;
							}
							LA22: ;
						} LA13: ;
					}
				} LA11: ;
				LOC61 = 0;
				LOC61 = closedir(d_143054);
			}
			LA9: ;
		}
	}
	LA4: ;
	result = NIM_FALSE;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, enable_143095)(Sensorambientlight143032* this_143098) {
	NIM_BOOL result;
	NimStringDesc* source;
{	result = 0;
	source = nosjoinPath((*this_143098).path, (*this_143098).prefixelement);
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nosexistsDir(source);
		if (!LOC3) goto LA4;
		{
			NU8 kind_143103;
			NimStringDesc* pathelement_143104;
			DIR* d_143109;
			kind_143103 = 0;
			pathelement_143104 = 0;
			d_143109 = opendir(source->data);
			{
				int LOC83;
				if (!!((d_143109 == NIM_NIL))) goto LA9;
				{
					while (1) {
						{
							struct dirent* x_143111;
							NimStringDesc* y_143113;
							x_143111 = readdir(d_143109);
							{
								if (!(x_143111 == NIM_NIL)) goto LA16;
								goto LA11;
							}
							LA16: ;
							y_143113 = cstrToNimstr(((NCSTRING) ((*x_143111).d_name)));
							{
								NIM_BOOL LOC20;
								struct stat s_143115;
								NU8 k_143117;
								LOC20 = 0;
								LOC20 = !(eqStrings(y_143113, ((NimStringDesc*) &TMP171)));
								if (!(LOC20)) goto LA21;
								LOC20 = !(eqStrings(y_143113, ((NimStringDesc*) &TMP172)));
								LA21: ;
								if (!LOC20) goto LA22;
								memset((void*)(&s_143115), 0, sizeof(s_143115));
								{
									if (!NIM_TRUE) goto LA26;
									y_143113 = HEX2F_122481(source, y_143113);
								}
								LA26: ;
								k_143117 = ((NU8) 0);
								{
									if (!!(((*x_143111).d_type == ((NI8) 0)))) goto LA30;
									{
										if (!((*x_143111).d_type == ((NI8) 4))) goto LA34;
										k_143117 = ((NU8) 2);
									}
									LA34: ;
									{
										if (!((*x_143111).d_type == ((NI8) 10))) goto LA38;
										{
											NIM_BOOL LOC42;
											LOC42 = 0;
											LOC42 = direxists_126020(y_143113);
											if (!LOC42) goto LA43;
											k_143117 = ((NU8) 3);
										}
										goto LA40;
										LA43: ;
										{
											k_143117 = (NU8)(k_143117 + ((NI) 1));
										}
										LA40: ;
									}
									LA38: ;
									kind_143103 = k_143117;
									pathelement_143104 = y_143113;
									{
										NI LOC48;
										LOC48 = 0;
										LOC48 = nsuFindStr(pathelement_143104, ((NimStringDesc*) &TMP178), ((NI) 0));
										if (!!((LOC48 == ((NI) -1)))) goto LA49;
										{
											NimStringDesc* LOC53;
											NIM_BOOL LOC54;
											LOC53 = 0;
											LOC53 = getfilecontents_143007(pathelement_143104);
											LOC54 = 0;
											LOC54 = parsebool_101305(LOC53);
											if (!!(LOC54)) goto LA55;
											result = setfilecontents_143019(pathelement_143104, ((NimStringDesc*) &TMP190));
											goto BeforeRet;
										}
										LA55: ;
									}
									LA49: ;
									goto LA13;
								}
								LA30: ;
								{
									int LOC59;
									LOC59 = 0;
									LOC59 = lstat(y_143113->data, (&s_143115));
									if (!(LOC59 < ((NI32) 0))) goto LA60;
									goto LA11;
								}
								LA60: ;
								{
									NIM_BOOL LOC64;
									LOC64 = 0;
									LOC64 = S_ISDIR(s_143115.st_mode);
									if (!LOC64) goto LA65;
									k_143117 = ((NU8) 2);
								}
								LA65: ;
								{
									NIM_BOOL LOC69;
									LOC69 = 0;
									LOC69 = S_ISLNK(s_143115.st_mode);
									if (!LOC69) goto LA70;
									k_143117 = (NU8)(k_143117 + ((NI) 1));
								}
								LA70: ;
								kind_143103 = k_143117;
								pathelement_143104 = y_143113;
								{
									NI LOC74;
									LOC74 = 0;
									LOC74 = nsuFindStr(pathelement_143104, ((NimStringDesc*) &TMP178), ((NI) 0));
									if (!!((LOC74 == ((NI) -1)))) goto LA75;
									{
										NimStringDesc* LOC79;
										NIM_BOOL LOC80;
										LOC79 = 0;
										LOC79 = getfilecontents_143007(pathelement_143104);
										LOC80 = 0;
										LOC80 = parsebool_101305(LOC79);
										if (!!(LOC80)) goto LA81;
										result = setfilecontents_143019(pathelement_143104, ((NimStringDesc*) &TMP190));
										goto BeforeRet;
									}
									LA81: ;
								}
								LA75: ;
							}
							LA22: ;
						} LA13: ;
					}
				} LA11: ;
				LOC83 = 0;
				LOC83 = closedir(d_143109);
			}
			LA9: ;
		}
	}
	LA4: ;
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NF, HEX2F_90317)(NI x, NI y) {
	NF result;
	result = 0;
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	return result;
}

static N_INLINE(NI, percent_144013)(Normalizer144007* this_144016, NI raw) {
	NI result;
	NF LOC9;
{	result = 0;
	{
		if (!((*this_144016).max < raw)) goto LA3;
		result = (*this_144016).max;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(raw < (*this_144016).min)) goto LA7;
		result = (*this_144016).min;
		goto BeforeRet;
	}
	LA7: ;
	LOC9 = 0;
	LOC9 = HEX2F_90317(raw, (*this_144016).max);
	result = ((NI) (((NF)(LOC9) * (NF)(1.0000000000000000e+02))));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, intensity_143081)(Sensorambientlight143032* this_143084) {
	NI result;
	NimStringDesc* source;
{	result = 0;
	source = nosjoinPath((*this_143084).path, (*this_143084).prefixintensity);
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = nosexistsFile(source);
		if (!LOC3) goto LA4;
		LOC6 = 0;
		LOC6 = getfilecontents_143007(source);
		result = nsuParseInt(LOC6);
		goto BeforeRet;
	}
	LA4: ;
	result = ((NI) 0);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, main_172004)(NimStringDesc* file, NimStringDesc* log) {
	Configambientlight170049 config;
	Configambientlight170049 LOC1;
	NI timeout;
	NimStringDesc* LOC2;
	NI intensitymin;
	NimStringDesc* LOC3;
	NI intensitymax;
	NimStringDesc* LOC4;
	NI intensitythreshold;
	NimStringDesc* LOC5;
	NI backlightmin;
	NimStringDesc* LOC6;
	NI backlightmax;
	NimStringDesc* LOC7;
	NimStringDesc* locationsensor;
	NimStringDesc* locationscript;
	RollingfileloggerHEX3Aobjecttype168061* LOC8;
	LoggerHEX3Aobjecttype168052* LOC9;
	Commandstarter161005 starter;
	Commandstarter161005 LOC52;
	Sensorfinder143137 sensorfinder;
	Sensorfinder143137 LOC53;
	Normalizer144007 normalizerbacklight;
	Normalizer144007 LOC54;
	Normalizer144007 normalizerintencity;
	Normalizer144007 LOC55;
	Sensorambientlight143032 sensor;
	NI previous;
	memset((void*)(&config), 0, sizeof(config));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.path = copyString(file);
	memcpy((void*)(&config), (NIM_CONST void*)(&LOC1), sizeof(config));
	LOC2 = 0;
	LOC2 = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP140));
	timeout = nsuParseInt(LOC2);
	LOC3 = 0;
	LOC3 = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP141));
	intensitymin = nsuParseInt(LOC3);
	LOC4 = 0;
	LOC4 = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP142));
	intensitymax = nsuParseInt(LOC4);
	LOC5 = 0;
	LOC5 = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP143));
	intensitythreshold = nsuParseInt(LOC5);
	LOC6 = 0;
	LOC6 = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP144));
	backlightmin = nsuParseInt(LOC6);
	LOC7 = 0;
	LOC7 = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP145));
	backlightmax = nsuParseInt(LOC7);
	locationsensor = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP146));
	locationscript = get_170060((&config), ((NimStringDesc*) &TMP139), ((NimStringDesc*) &TMP147));
	LOC8 = 0;
	LOC8 = newrollingfilelogger_168490(log, ((NU8) 2), ((NU8) 2), ((NimStringDesc*) &TMP163), ((NI) 1000), ((NI) -1));
	LOC9 = 0;
	LOC9 = &LOC8->Sup.Sup;
	addhandler_168896(LOC9);
	{
		TY168231 LOC14;
		TY168231 LOC15;
		if (!(level_168627 <= ((NU8) 2))) goto LA12;
		memset((void*)LOC14, 0, sizeof(LOC14));
		memset((void*)LOC15, 0, sizeof(LOC15));
		LOC15[0] = nsuIntToStr(intensitymin, ((NI) 1));
		LOC14[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP164), LOC15, 1);
		logloop_168638(((NU8) 2), LOC14, 1);
	}
	LA12: ;
	{
		TY168231 LOC20;
		TY168231 LOC21;
		if (!(level_168627 <= ((NU8) 2))) goto LA18;
		memset((void*)LOC20, 0, sizeof(LOC20));
		memset((void*)LOC21, 0, sizeof(LOC21));
		LOC21[0] = nsuIntToStr(intensitymax, ((NI) 1));
		LOC20[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP165), LOC21, 1);
		logloop_168638(((NU8) 2), LOC20, 1);
	}
	LA18: ;
	{
		TY168231 LOC26;
		TY168231 LOC27;
		if (!(level_168627 <= ((NU8) 2))) goto LA24;
		memset((void*)LOC26, 0, sizeof(LOC26));
		memset((void*)LOC27, 0, sizeof(LOC27));
		LOC27[0] = nsuIntToStr(intensitythreshold, ((NI) 1));
		LOC26[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP166), LOC27, 1);
		logloop_168638(((NU8) 2), LOC26, 1);
	}
	LA24: ;
	{
		TY168231 LOC32;
		TY168231 LOC33;
		if (!(level_168627 <= ((NU8) 2))) goto LA30;
		memset((void*)LOC32, 0, sizeof(LOC32));
		memset((void*)LOC33, 0, sizeof(LOC33));
		LOC33[0] = nsuIntToStr(backlightmin, ((NI) 1));
		LOC32[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP167), LOC33, 1);
		logloop_168638(((NU8) 2), LOC32, 1);
	}
	LA30: ;
	{
		TY168231 LOC38;
		TY168231 LOC39;
		if (!(level_168627 <= ((NU8) 2))) goto LA36;
		memset((void*)LOC38, 0, sizeof(LOC38));
		memset((void*)LOC39, 0, sizeof(LOC39));
		LOC39[0] = nsuIntToStr(backlightmax, ((NI) 1));
		LOC38[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP168), LOC39, 1);
		logloop_168638(((NU8) 2), LOC38, 1);
	}
	LA36: ;
	{
		TY168231 LOC44;
		TY168231 LOC45;
		if (!(level_168627 <= ((NU8) 2))) goto LA42;
		memset((void*)LOC44, 0, sizeof(LOC44));
		memset((void*)LOC45, 0, sizeof(LOC45));
		LOC45[0] = copyString(locationsensor);
		LOC44[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP169), LOC45, 1);
		logloop_168638(((NU8) 2), LOC44, 1);
	}
	LA42: ;
	{
		TY168231 LOC50;
		TY168231 LOC51;
		if (!(level_168627 <= ((NU8) 2))) goto LA48;
		memset((void*)LOC50, 0, sizeof(LOC50));
		memset((void*)LOC51, 0, sizeof(LOC51));
		LOC51[0] = copyString(locationscript);
		LOC50[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP170), LOC51, 1);
		logloop_168638(((NU8) 2), LOC50, 1);
	}
	LA48: ;
	memset((void*)(&starter), 0, sizeof(starter));
	memset((void*)(&LOC52), 0, sizeof(LOC52));
	memset((void*)(&LOC52), 0, sizeof(LOC52));
	LOC52.path = copyString(locationscript);
	starter.path = LOC52.path;
	memset((void*)(&sensorfinder), 0, sizeof(sensorfinder));
	memset((void*)(&LOC53), 0, sizeof(LOC53));
	memset((void*)(&LOC53), 0, sizeof(LOC53));
	LOC53.path = copyString(locationsensor);
	sensorfinder.path = LOC53.path;
	memset((void*)(&LOC54), 0, sizeof(LOC54));
	LOC54.min = backlightmin;
	LOC54.max = backlightmax;
	normalizerbacklight = LOC54;
	memset((void*)(&LOC55), 0, sizeof(LOC55));
	LOC55.min = intensitymin;
	LOC55.max = intensitymax;
	normalizerintencity = LOC55;
	memset((void*)(&sensor), 0, sizeof(sensor));
	chckNil((void*)(&sensor));
	memset((void*)(&sensor), 0, sizeof(sensor));
	get_143234((&sensorfinder), ((NimStringDesc*) &TMP139), (&sensor));
	{
		while (1) {
			NIM_BOOL LOC58;
			NIM_BOOL LOC59;
			NIM_BOOL LOC61;
			LOC58 = 0;
			LOC59 = 0;
			LOC59 = exists_143040((&sensor));
			LOC58 = !(LOC59);
			if (LOC58) goto LA60;
			LOC61 = 0;
			LOC61 = enable_143095((&sensor));
			LOC58 = !(LOC61);
			LA60: ;
			if (!LOC58) goto LA57;
			{
				TY168231 LOC66;
				NimStringDesc* LOC67;
				if (!(level_168627 <= ((NU8) 4))) goto LA64;
				memset((void*)LOC66, 0, sizeof(LOC66));
				LOC67 = 0;
				LOC67 = nsuIntToStr(timeout, ((NI) 1));
				LOC66[0] = nsuFormatSingleElem(((NimStringDesc*) &TMP191), LOC67);
				logloop_168638(((NU8) 4), LOC66, 1);
			}
			LA64: ;
			nossleep(timeout);
		} LA57: ;
	}
	setcontrolchook_20201(((TY20205) (handler_171012)));
	previous = ((NI) 0);
	{
		while (1) {
			NI current;
			NI LOC70;
			LOC70 = 0;
			LOC70 = intensity_143081((&sensor));
			current = percent_144013((&normalizerintencity), LOC70);
			{
				NI backlight;
				if (!(intensitythreshold <= ((NI)(current - previous) > 0? ((NI)(current - previous)) : -((NI)(current - previous))))) goto LA73;
				backlight = percent_144013((&normalizerbacklight), current);
				{
					TY168231 LOC79;
					TY172717 LOC80;
					if (!(level_168627 <= ((NU8) 1))) goto LA77;
					memset((void*)LOC79, 0, sizeof(LOC79));
					memset((void*)LOC80, 0, sizeof(LOC80));
					LOC80[0] = nsuIntToStr(current, ((NI) 1));
					LOC80[1] = nsuIntToStr(backlight, ((NI) 1));
					LOC79[0] = nsuFormatOpenArray(((NimStringDesc*) &TMP194), LOC80, 2);
					logloop_168638(((NU8) 1), LOC79, 1);
				}
				LA77: ;
				{
					NI error_172731;
					NimStringDesc* HEX3Atmp_172760;
					error_172731 = 0;
					HEX3Atmp_172760 = 0;
					HEX3Atmp_172760 = nsuIntToStr(backlight, ((NI) 1));
					{
						NimStringDesc* script_172766;
						script_172766 = 0;
						{
							NIM_BOOL LOC85;
							LOC85 = 0;
							LOC85 = direxists_126020(starter.path);
							if (!LOC85) goto LA86;
							{
								NU8 kind_172768;
								NimStringDesc* path_172770;
								NimStringDesc* HEX3Atmp_172772;
								DIR* d_172774;
								kind_172768 = 0;
								path_172770 = 0;
								HEX3Atmp_172772 = 0;
								HEX3Atmp_172772 = starter.path;
								d_172774 = opendir(HEX3Atmp_172772->data);
								{
									int LOC169;
									if (!!((d_172774 == NIM_NIL))) goto LA91;
									{
										while (1) {
											{
												struct dirent* x_172776;
												NimStringDesc* y_172778;
												x_172776 = readdir(d_172774);
												{
													if (!(x_172776 == NIM_NIL)) goto LA98;
													goto LA93;
												}
												LA98: ;
												y_172778 = cstrToNimstr(((NCSTRING) ((*x_172776).d_name)));
												{
													NIM_BOOL LOC102;
													struct stat s_172780;
													NU8 k_172782;
													LOC102 = 0;
													LOC102 = !(eqStrings(y_172778, ((NimStringDesc*) &TMP171)));
													if (!(LOC102)) goto LA103;
													LOC102 = !(eqStrings(y_172778, ((NimStringDesc*) &TMP172)));
													LA103: ;
													if (!LOC102) goto LA104;
													memset((void*)(&s_172780), 0, sizeof(s_172780));
													{
														if (!NIM_TRUE) goto LA108;
														y_172778 = HEX2F_122481(HEX3Atmp_172772, y_172778);
													}
													LA108: ;
													k_172782 = ((NU8) 0);
													{
														if (!!(((*x_172776).d_type == ((NI8) 0)))) goto LA112;
														{
															if (!((*x_172776).d_type == ((NI8) 4))) goto LA116;
															k_172782 = ((NU8) 2);
														}
														LA116: ;
														{
															if (!((*x_172776).d_type == ((NI8) 10))) goto LA120;
															{
																NIM_BOOL LOC124;
																LOC124 = 0;
																LOC124 = direxists_126020(y_172778);
																if (!LOC124) goto LA125;
																k_172782 = ((NU8) 3);
															}
															goto LA122;
															LA125: ;
															{
																k_172782 = (NU8)(k_172782 + ((NI) 1));
															}
															LA122: ;
														}
														LA120: ;
														kind_172768 = k_172782;
														path_172770 = y_172778;
														{
															NIM_BOOL LOC130;
															TY172717 LOC133;
															NimStringDesc* LOC134;
															LOC130 = 0;
															LOC130 = nosexistsFile(path_172770);
															if (!LOC130) goto LA131;
															script_172766 = path_172770;
															memset((void*)LOC133, 0, sizeof(LOC133));
															LOC133[0] = copyString(script_172766);
															LOC133[1] = copyString(HEX3Atmp_172760);
															LOC134 = 0;
															LOC134 = nsuFormatOpenArray(((NimStringDesc*) &TMP195), LOC133, 2);
															error_172731 = nospexecCmd(LOC134);
															{
																TY168231 LOC139;
																NimStringDesc* LOC140;
																if (!(level_168627 <= ((NU8) 1))) goto LA137;
																memset((void*)LOC139, 0, sizeof(LOC139));
																LOC140 = 0;
																LOC140 = nsuIntToStr(error_172731, ((NI) 1));
																LOC139[0] = nsuFormatSingleElem(((NimStringDesc*) &TMP196), LOC140);
																logloop_168638(((NU8) 1), LOC139, 1);
															}
															LA137: ;
														}
														LA131: ;
														goto LA95;
													}
													LA112: ;
													{
														int LOC143;
														LOC143 = 0;
														LOC143 = lstat(y_172778->data, (&s_172780));
														if (!(LOC143 < ((NI32) 0))) goto LA144;
														goto LA93;
													}
													LA144: ;
													{
														NIM_BOOL LOC148;
														LOC148 = 0;
														LOC148 = S_ISDIR(s_172780.st_mode);
														if (!LOC148) goto LA149;
														k_172782 = ((NU8) 2);
													}
													LA149: ;
													{
														NIM_BOOL LOC153;
														LOC153 = 0;
														LOC153 = S_ISLNK(s_172780.st_mode);
														if (!LOC153) goto LA154;
														k_172782 = (NU8)(k_172782 + ((NI) 1));
													}
													LA154: ;
													kind_172768 = k_172782;
													path_172770 = y_172778;
													{
														NIM_BOOL LOC158;
														TY172717 LOC161;
														NimStringDesc* LOC162;
														LOC158 = 0;
														LOC158 = nosexistsFile(path_172770);
														if (!LOC158) goto LA159;
														script_172766 = path_172770;
														memset((void*)LOC161, 0, sizeof(LOC161));
														LOC161[0] = copyString(script_172766);
														LOC161[1] = copyString(HEX3Atmp_172760);
														LOC162 = 0;
														LOC162 = nsuFormatOpenArray(((NimStringDesc*) &TMP195), LOC161, 2);
														error_172731 = nospexecCmd(LOC162);
														{
															TY168231 LOC167;
															NimStringDesc* LOC168;
															if (!(level_168627 <= ((NU8) 1))) goto LA165;
															memset((void*)LOC167, 0, sizeof(LOC167));
															LOC168 = 0;
															LOC168 = nsuIntToStr(error_172731, ((NI) 1));
															LOC167[0] = nsuFormatSingleElem(((NimStringDesc*) &TMP196), LOC168);
															logloop_168638(((NU8) 1), LOC167, 1);
														}
														LA165: ;
													}
													LA159: ;
												}
												LA104: ;
											} LA95: ;
										}
									} LA93: ;
									LOC169 = 0;
									LOC169 = closedir(d_172774);
								}
								LA91: ;
							}
						}
						LA86: ;
					}
				}
				previous = current;
			}
			LA73: ;
			nossleep(timeout);
		}
	}
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(obj == subclass)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!((*obj).base == subclass)) goto LA7;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA11: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA15: ;
	result = isobjslowpath_25161(obj, subclass, cache);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, log_168211)(LoggerHEX3Aobjecttype168052* logger, NU8 level, NimStringDesc** args, NI argsLen0) {
	{
		if (!((logger) && ((*logger).Sup.m_type == (&NTI168061)))) goto LA3;
		log_168565(((RollingfileloggerHEX3Aobjecttype168061*) (logger)), level, args, argsLen0);
	}
	goto LA1;
	LA3: ;
	{
		if (!((logger) && (isObjWithCache((*logger).Sup.m_type, (&NTI168058), Nim_OfCheck_CACHE1)))) goto LA6;
		log_168289(((FileloggerHEX3Aobjecttype168058*) (logger)), level, args, argsLen0);
	}
	goto LA1;
	LA6: ;
	{
		if (!((logger) && ((*logger).Sup.m_type == (&NTI168056)))) goto LA9;
		log_168216(((ConsoleloggerHEX3Aobjecttype168056*) (logger)), level, args, argsLen0);
	}
	goto LA1;
	LA9: ;
	{
		if (!((logger) && (isObjWithCache((*logger).Sup.m_type, (&NTI168052), Nim_OfCheck_CACHE2)))) goto LA12;
		log_168201(logger, level, args, argsLen0);
	}
	goto LA1;
	LA12: ;
	LA1: ;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_parseutilsDatInit000();
	HEX00_strutilsDatInit000();
	HEX00_timesDatInit000();
	HEX00_posixDatInit000();
	HEX00_osDatInit000();
	HEX00_streamsDatInit000();
	HEX00_sensorsDatInit000();
	HEX00_normalizerDatInit000();
	HEX00_etcprivDatInit000();
	HEX00_hashesDatInit000();
	HEX00_strtabsDatInit000();
	HEX00_linuxDatInit000();
	HEX00_cpuinfoDatInit000();
	HEX00_osprocDatInit000();
	HEX00_starterDatInit000();
	HEX00_lexbaseDatInit000();
	HEX00_parsecfgDatInit000();
	HEX00_loggingDatInit000();
	HEX00_configDatInit000();
	HEX00_signalDatInit000();
	monitor_ambient_lightDatInit000();
	HEX00_parseutilsInit000();
	HEX00_strutilsInit000();
	HEX00_timesInit000();
	HEX00_posixInit000();
	HEX00_osInit000();
	HEX00_streamsInit000();
	HEX00_sensorsInit000();
	HEX00_normalizerInit000();
	HEX00_etcprivInit000();
	HEX00_hashesInit000();
	HEX00_strtabsInit000();
	HEX00_linuxInit000();
	HEX00_cpuinfoInit000();
	HEX00_osprocInit000();
	HEX00_starterInit000();
	HEX00_lexbaseInit000();
	HEX00_parsecfgInit000();
	HEX00_loggingInit000();
	HEX00_configInit000();
	HEX00_signalInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	monitor_ambient_lightInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, monitor_ambient_lightInit000)(void) {
	main_172004(((NimStringDesc*) &TMP197), ((NimStringDesc*) &TMP198));
}

NIM_EXTERNC N_NOINLINE(void, monitor_ambient_lightDatInit000)(void) {
}

