/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/osproc.o /home/sensey/Projects/nim-test/nimcache/osproc.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};

N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = system(command->data);
	result = ((NI) ((NI32)((NU32)(LOC1) >> (NU32)(((NI32) 8)))));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_osprocInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_osprocDatInit000)(void) {
}

