/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/sensors.o /home/sensey/Projects/nim-test/nimcache/sensors.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Filestreamobj141467 Filestreamobj141467;
typedef struct Streamobj140227 Streamobj140227;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TY162040[32];
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, TY140228) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY140232) (Streamobj140227* s);
typedef N_NIMCALL_PTR(void, TY140236) (Streamobj140227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY140241) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NI, TY140245) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY140251) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140257) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140263) (Streamobj140227* s);
struct  Streamobj140227  {
  TNimObject Sup;
TY140228 closeimpl;
TY140232 atendimpl;
TY140236 setpositionimpl;
TY140241 getpositionimpl;
TY140245 readdataimpl;
TY140251 peekdataimpl;
TY140257 writedataimpl;
TY140263 flushimpl;
};
struct  Filestreamobj141467  {
  Streamobj140227 Sup;
FILE* f;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(Filestreamobj141467*, newfilestream_141559)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, TY162040 chars);
N_NIMCALL(NimStringDesc*, readall_140392)(Streamobj140227* s);
N_NIMCALL(void, close_140291)(Streamobj140227* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, write_140483)(Streamobj140227* s, NimStringDesc* x);
static NIM_CONST TY162040 TMP175 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;

N_NIMCALL(NimStringDesc*, getfilecontents_143007)(NimStringDesc* source) {
	NimStringDesc* result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		Filestreamobj141467* stream;
		NimStringDesc* content;
		Streamobj140227* LOC6;
		NimStringDesc* LOC7;
		Streamobj140227* LOC8;
		LOC3 = 0;
		LOC3 = nosexistsFile(source);
		if (!LOC3) goto LA4;
		stream = newfilestream_141559(source, ((NU8) 0));
		LOC6 = 0;
		LOC6 = &stream->Sup;
		LOC7 = 0;
		LOC7 = readall_140392(LOC6);
		content = nsuStrip(LOC7, NIM_TRUE, NIM_TRUE, TMP175);
		LOC8 = 0;
		LOC8 = &stream->Sup;
		close_140291(LOC8);
		result = copyString(content);
		goto BeforeRet;
	}
	LA4: ;
	result = copyString(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, setfilecontents_143019)(NimStringDesc* source, NimStringDesc* value) {
	NIM_BOOL result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		Filestreamobj141467* stream;
		Streamobj140227* LOC6;
		Streamobj140227* LOC7;
		LOC3 = 0;
		LOC3 = nosexistsFile(source);
		if (!LOC3) goto LA4;
		stream = newfilestream_141559(source, ((NU8) 1));
		LOC6 = 0;
		LOC6 = &stream->Sup;
		write_140483(LOC6, value);
		LOC7 = 0;
		LOC7 = &stream->Sup;
		close_140291(LOC7);
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA4: ;
	result = NIM_FALSE;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_sensorsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_sensorsDatInit000)(void) {
}

