/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/signal.o /home/sensey/Projects/nim-test/nimcache/signal.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY168231[1];
N_NIMCALL(void, logloop_168638)(NU8 level, NimStringDesc** args, NI argsLen0);
STRING_LITERAL(TMP193, "interrupted by SIGINT", 21);
NIM_CONST TY168231 TMP192 = {((NimStringDesc*) &TMP193)}
;
extern NU8 level_168627;

N_NOCONV(void, handler_171012)(void) {
	{
		if (!(level_168627 <= ((NU8) 2))) goto LA3;
		logloop_168638(((NU8) 2), TMP192, 1);
	}
	LA3: ;
	exit(((NI) 0));
}
NIM_EXTERNC N_NOINLINE(void, HEX00_signalInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_signalDatInit000)(void) {
}

