/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/starter.o /home/sensey/Projects/nim-test/nimcache/starter.c */
#define NIM_INTBITS 64

#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, HEX00_starterInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_starterDatInit000)(void) {
}

