/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/streams.o /home/sensey/Projects/nim-test/nimcache/streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <setjmp.h>
typedef struct Filestreamobj141467 Filestreamobj141467;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Streamobj140227 Streamobj140227;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Ioerror4031 Ioerror4031;
typedef struct Systemerror4029 Systemerror4029;
typedef struct Cell48947 Cell48947;
typedef struct Cellseq48963 Cellseq48963;
typedef struct Gcheap51018 Gcheap51018;
typedef struct Gcstack51016 Gcstack51016;
typedef struct Cellset48959 Cellset48959;
typedef struct Pagedesc48955 Pagedesc48955;
typedef struct Memregion30891 Memregion30891;
typedef struct Smallchunk30843 Smallchunk30843;
typedef struct Llchunk30885 Llchunk30885;
typedef struct Bigchunk30845 Bigchunk30845;
typedef struct Intset30817 Intset30817;
typedef struct Trunk30813 Trunk30813;
typedef struct Avlnode30889 Avlnode30889;
typedef struct Gcstat51014 Gcstat51014;
typedef struct Basechunk30841 Basechunk30841;
typedef struct Freecell30833 Freecell30833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, TY140228) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY140232) (Streamobj140227* s);
typedef N_NIMCALL_PTR(void, TY140236) (Streamobj140227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY140241) (Streamobj140227* s);
typedef N_NIMCALL_PTR(NI, TY140245) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY140251) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140257) (Streamobj140227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY140263) (Streamobj140227* s);
struct  Streamobj140227  {
  TNimObject Sup;
TY140228 closeimpl;
TY140232 atendimpl;
TY140236 setpositionimpl;
TY140241 getpositionimpl;
TY140245 readdataimpl;
TY140251 peekdataimpl;
TY140257 writedataimpl;
TY140263 flushimpl;
};
struct  Filestreamobj141467  {
  Streamobj140227 Sup;
FILE* f;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
struct  Systemerror4029  {
  Exception Sup;
};
struct  Ioerror4031  {
  Systemerror4029 Sup;
};
struct  Cell48947  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48963  {
NI len;
NI cap;
Cell48947** d;
};
struct  Cellset48959  {
NI counter;
NI max;
Pagedesc48955* head;
Pagedesc48955** data;
};
typedef Smallchunk30843* TY30906[512];
typedef Trunk30813* Trunkbuckets30815[256];
struct  Intset30817  {
Trunkbuckets30815 data;
};
struct  Memregion30891  {
NI minlargeobj;
NI maxlargeobj;
TY30906 freesmallchunks;
Llchunk30885* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30845* freechunkslist;
Intset30817 chunkstarts;
Avlnode30889* root;
Avlnode30889* deleted;
Avlnode30889* last;
Avlnode30889* freeavlnodes;
};
struct  Gcstat51014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51018  {
Gcstack51016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48963 zct;
Cellseq48963 decstack;
Cellset48959 cycleroots;
Cellseq48963 tempstack;
NI recgclock;
Memregion30891 region;
Gcstat51014 stat;
};
struct  Gcstack51016  {
Gcstack51016* prev;
Gcstack51016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30822[8];
struct  Pagedesc48955  {
Pagedesc48955* next;
NI key;
TY30822 bits;
};
struct  Basechunk30841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30843  {
  Basechunk30841 Sup;
Smallchunk30843* next;
Smallchunk30843* prev;
Freecell30833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30885  {
NI size;
NI acc;
Llchunk30885* next;
};
struct  Bigchunk30845  {
  Basechunk30841 Sup;
Bigchunk30845* next;
Bigchunk30845* prev;
NI align;
NF data;
};
struct  Trunk30813  {
Trunk30813* next;
NI key;
TY30822 bits;
};
typedef Avlnode30889* TY30896[2];
struct  Avlnode30889  {
TY30896 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30833  {
Freecell30833* next;
NI zerofield;
};
N_NIMCALL(NIM_BOOL, open_16803)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(Filestreamobj141467*, newfilestream_141544)(FILE* f);
N_NIMCALL(void, TMP106)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, fsclose_141471)(Streamobj140227* s);
N_NIMCALL(NIM_BOOL, fsatend_141495)(Streamobj140227* s);
N_NIMCALL(NIM_BOOL, endoffile_16860)(FILE* f);
N_NIMCALL(void, fssetposition_141502)(Streamobj140227* s, NI pos);
N_NIMCALL(void, setfilepos_16987)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_141509)(Streamobj140227* s);
N_NIMCALL(NI64, getfilepos_16991)(FILE* f);
N_NIMCALL(NI, fsreaddata_141517)(Streamobj140227* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_16960)(FILE* f, void* buffer, NI len);
N_NIMCALL(NI, fspeekdata_141526)(Streamobj140227* s, void* buffer, NI buflen);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, fswritedata_141536)(Streamobj140227* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_16982)(FILE* f, void* buffer, NI len);
N_NIMCALL(Ioerror4031*, neweio_140205)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell48947*, usrtocell_52646)(void* usr);
static N_INLINE(void, rtladdzct_54204)(Cell48947* c);
N_NOINLINE(void, addzct_52617)(Cellseq48963* s, Cell48947* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, fsflush_141489)(Streamobj140227* s);
N_NIMCALL(void, TMP114)(void* p, NI op);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NI, readdata_140380)(Streamobj140227* s, void* buffer, NI buflen);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(void, writedata_140448)(Streamobj140227* s, void* buffer, NI buflen);
STRING_LITERAL(TMP112, "cannot write to stream", 22);
extern TNimType NTI4011; /* RootObj */
TNimType NTI140227; /* StreamObj */
TNimType NTI140228; /* proc (s: Stream){.gcsafe.} */
TNimType NTI140232; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI140236; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI140241; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI140245; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI140251; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI140257; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI140263; /* proc (s: Stream){.gcsafe.} */
TNimType NTI141467; /* FileStreamObj */
extern TNimType NTI16404; /* File */
TNimType NTI141465; /* FileStream */
extern TSafePoint* exchandler_20843;
extern TNimType NTI82817; /* ref IOError */
extern TNimType NTI4031; /* IOError */
extern Gcheap51018 gch_51059;
TNimType NTI140225; /* Stream */
N_NIMCALL(void, TMP106)(void* p, NI op) {
	Filestreamobj141467* a;
	a = (Filestreamobj141467*)p;
}

N_NIMCALL(void, fsclose_141471)(Streamobj140227* s) {
	{
		if (!!(((*((Filestreamobj141467*) (s))).f == NIM_NIL))) goto LA3;
		fclose((*((Filestreamobj141467*) (s))).f);
		(*((Filestreamobj141467*) (s))).f = NIM_NIL;
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, fsatend_141495)(Streamobj140227* s) {
	NIM_BOOL result;
{	result = 0;
	result = endoffile_16860((*((Filestreamobj141467*) (s))).f);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, fssetposition_141502)(Streamobj140227* s, NI pos) {
	setfilepos_16987((*((Filestreamobj141467*) (s))).f, ((NI64) (pos)));
}

N_NIMCALL(NI, fsgetposition_141509)(Streamobj140227* s) {
	NI result;
	NI64 LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = getfilepos_16991((*((Filestreamobj141467*) (s))).f);
	result = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, fsreaddata_141517)(Streamobj140227* s, void* buffer, NI buflen) {
	NI result;
	result = 0;
	result = readbuffer_16960((*((Filestreamobj141467*) (s))).f, buffer, ((NI) (buflen)));
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

N_NIMCALL(NI, fspeekdata_141526)(Streamobj140227* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP109;
	result = 0;
	pos = fsgetposition_141509(s);
	pushSafePoint(&TMP109);
	TMP109.status = setjmp(TMP109.context);
	if (TMP109.status == 0) {
		result = readbuffer_16960((*((Filestreamobj141467*) (s))).f, buffer, ((NI) (buflen)));
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		fssetposition_141502(s, pos);
	}
	if (TMP109.status != 0) reraiseException();
	return result;
}

static N_INLINE(Cell48947*, usrtocell_52646)(void* usr) {
	Cell48947* result;
	result = 0;
	result = ((Cell48947*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell48947))))));
	return result;
}

static N_INLINE(void, rtladdzct_54204)(Cell48947* c) {
	addzct_52617((&gch_51059.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell48947* c;
	c = usrtocell_52646(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_54204(c);
	}
	LA3: ;
}

N_NIMCALL(Ioerror4031*, neweio_140205)(NimStringDesc* msg) {
	Ioerror4031* result;
	NimStringDesc* LOC1;
	result = 0;
	result = (Ioerror4031*) newObj((&NTI82817), sizeof(Ioerror4031));
	(*result).Sup.Sup.Sup.m_type = (&NTI4031);
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	return result;
}

N_NIMCALL(void, fswritedata_141536)(Streamobj140227* s, void* buffer, NI buflen) {
	{
		NI LOC3;
		Ioerror4031* LOC6;
		LOC3 = 0;
		LOC3 = writebuffer_16982((*((Filestreamobj141467*) (s))).f, buffer, ((NI) (buflen)));
		if (!!((LOC3 == buflen))) goto LA4;
		LOC6 = 0;
		LOC6 = neweio_140205(((NimStringDesc*) &TMP112));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
}

N_NIMCALL(void, fsflush_141489)(Streamobj140227* s) {
	fflush((*((Filestreamobj141467*) (s))).f);
}

N_NIMCALL(Filestreamobj141467*, newfilestream_141544)(FILE* f) {
	Filestreamobj141467* result;
	result = 0;
	result = (Filestreamobj141467*) newObj((&NTI141465), sizeof(Filestreamobj141467));
	(*result).Sup.Sup.m_type = (&NTI141467);
	(*result).f = f;
	(*result).Sup.closeimpl = fsclose_141471;
	(*result).Sup.atendimpl = fsatend_141495;
	(*result).Sup.setpositionimpl = fssetposition_141502;
	(*result).Sup.getpositionimpl = fsgetposition_141509;
	(*result).Sup.readdataimpl = fsreaddata_141517;
	(*result).Sup.peekdataimpl = fspeekdata_141526;
	(*result).Sup.writedataimpl = fswritedata_141536;
	(*result).Sup.flushimpl = fsflush_141489;
	return result;
}

N_NIMCALL(Filestreamobj141467*, newfilestream_141559)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj141467* result;
	FILE* f;
	result = 0;
	f = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_16803(&f, filename, mode, ((NI) -1));
		if (!LOC3) goto LA4;
		result = newfilestream_141544(f);
	}
	LA4: ;
	return result;
}
N_NIMCALL(void, TMP114)(void* p, NI op) {
	Streamobj140227* a;
	a = (Streamobj140227*)p;
}

N_NIMCALL(NI, readdata_140380)(Streamobj140227* s, void* buffer, NI buflen) {
	NI result;
	result = 0;
	result = (*s).readdataimpl(s, buffer, buflen);
	return result;
}

N_NIMCALL(void, close_140291)(Streamobj140227* s) {
	{
		if (!!((*s).closeimpl == 0)) goto LA3;
		(*s).closeimpl(s);
	}
	LA3: ;
}

N_NIMCALL(NimStringDesc*, readall_140392)(Streamobj140227* s) {
	NimStringDesc* result;
	NI r;
	result = 0;
	result = mnewString(((NI) 1000));
	r = ((NI) 0);
	{
		while (1) {
			NI readbytes;
			readbytes = readdata_140380(s, ((void*) ((&result->data[r]))), ((NI) 1000));
			{
				if (!(readbytes < ((NI) 1000))) goto LA5;
				result = setLengthStr(result, ((NI) ((NI)(r + readbytes))));
				goto LA1;
			}
			LA5: ;
			r += ((NI) 1000);
			result = setLengthStr(result, ((NI) ((NI)(r + ((NI) 1000)))));
		}
	} LA1: ;
	return result;
}

N_NIMCALL(void, writedata_140448)(Streamobj140227* s, void* buffer, NI buflen) {
	(*s).writedataimpl(s, buffer, buflen);
}

N_NIMCALL(void, write_140483)(Streamobj140227* s, NimStringDesc* x) {
	writedata_140448(s, ((void*) (x->data)), (x ? x->Sup.len : 0));
}
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void) {
static TNimNode* TMP105[8];
static TNimNode TMP17[10];
NTI140227.size = sizeof(Streamobj140227);
NTI140227.kind = 17;
NTI140227.base = (&NTI4011);
NTI140227.flags = 1;
TMP105[0] = &TMP17[1];
NTI140228.size = sizeof(TY140228);
NTI140228.kind = 25;
NTI140228.base = 0;
NTI140228.flags = 3;
TMP17[1].kind = 1;
TMP17[1].offset = offsetof(Streamobj140227, closeimpl);
TMP17[1].typ = (&NTI140228);
TMP17[1].name = "closeImpl";
TMP105[1] = &TMP17[2];
NTI140232.size = sizeof(TY140232);
NTI140232.kind = 25;
NTI140232.base = 0;
NTI140232.flags = 3;
TMP17[2].kind = 1;
TMP17[2].offset = offsetof(Streamobj140227, atendimpl);
TMP17[2].typ = (&NTI140232);
TMP17[2].name = "atEndImpl";
TMP105[2] = &TMP17[3];
NTI140236.size = sizeof(TY140236);
NTI140236.kind = 25;
NTI140236.base = 0;
NTI140236.flags = 3;
TMP17[3].kind = 1;
TMP17[3].offset = offsetof(Streamobj140227, setpositionimpl);
TMP17[3].typ = (&NTI140236);
TMP17[3].name = "setPositionImpl";
TMP105[3] = &TMP17[4];
NTI140241.size = sizeof(TY140241);
NTI140241.kind = 25;
NTI140241.base = 0;
NTI140241.flags = 3;
TMP17[4].kind = 1;
TMP17[4].offset = offsetof(Streamobj140227, getpositionimpl);
TMP17[4].typ = (&NTI140241);
TMP17[4].name = "getPositionImpl";
TMP105[4] = &TMP17[5];
NTI140245.size = sizeof(TY140245);
NTI140245.kind = 25;
NTI140245.base = 0;
NTI140245.flags = 3;
TMP17[5].kind = 1;
TMP17[5].offset = offsetof(Streamobj140227, readdataimpl);
TMP17[5].typ = (&NTI140245);
TMP17[5].name = "readDataImpl";
TMP105[5] = &TMP17[6];
NTI140251.size = sizeof(TY140251);
NTI140251.kind = 25;
NTI140251.base = 0;
NTI140251.flags = 3;
TMP17[6].kind = 1;
TMP17[6].offset = offsetof(Streamobj140227, peekdataimpl);
TMP17[6].typ = (&NTI140251);
TMP17[6].name = "peekDataImpl";
TMP105[6] = &TMP17[7];
NTI140257.size = sizeof(TY140257);
NTI140257.kind = 25;
NTI140257.base = 0;
NTI140257.flags = 3;
TMP17[7].kind = 1;
TMP17[7].offset = offsetof(Streamobj140227, writedataimpl);
TMP17[7].typ = (&NTI140257);
TMP17[7].name = "writeDataImpl";
TMP105[7] = &TMP17[8];
NTI140263.size = sizeof(TY140263);
NTI140263.kind = 25;
NTI140263.base = 0;
NTI140263.flags = 3;
TMP17[8].kind = 1;
TMP17[8].offset = offsetof(Streamobj140227, flushimpl);
TMP17[8].typ = (&NTI140263);
TMP17[8].name = "flushImpl";
TMP17[0].len = 8; TMP17[0].kind = 2; TMP17[0].sons = &TMP105[0];
NTI140227.node = &TMP17[0];
NTI141467.size = sizeof(Filestreamobj141467);
NTI141467.kind = 17;
NTI141467.base = (&NTI140227);
NTI141467.flags = 1;
TMP17[9].kind = 1;
TMP17[9].offset = offsetof(Filestreamobj141467, f);
TMP17[9].typ = (&NTI16404);
TMP17[9].name = "f";
NTI141467.node = &TMP17[9];
NTI141465.size = sizeof(Filestreamobj141467*);
NTI141465.kind = 22;
NTI141465.base = (&NTI141467);
NTI141465.marker = TMP106;
NTI140225.size = sizeof(Streamobj140227*);
NTI140225.kind = 22;
NTI140225.base = (&NTI140227);
NTI140225.marker = TMP114;
}

