/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/sensey/Projects/nim-test/nimcache/times.o /home/sensey/Projects/nim-test/nimcache/times.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <time.h>
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Timeinfo107410 Timeinfo107410;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY107572 TY107572;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Timeinfo107410  {
  TNimObject Sup;
NI second;
NI minute;
NI hour;
NI monthday;
NU8 month;
NI year;
NU8 weekday;
NI yearday;
NIM_BOOL isdst;
NimStringDesc* tzname;
NI timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY108055[7];
struct TY107572 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
N_NIMCALL(void, getlocaltime_107477)(time_t t, Timeinfo107410* Result);
N_NIMCALL(void, tmtotimeinfo_108048)(struct tm* tm, NIM_BOOL local, Timeinfo107410* Result);
N_NIMCALL(void, gettzname_107570)(TY107572* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_107604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(time_t, gettime_107472)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
NIM_CONST TY108055 weekdays_108053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
STRING_LITERAL(TMP73, "UTC", 3);
extern TNimType NTI4011; /* RootObj */
TNimType NTI107410; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI107413; /* range 0..61(int) */
TNimType NTI107416; /* range 0..59(int) */
TNimType NTI107418; /* range 0..23(int) */
TNimType NTI107421; /* range 1..31(int) */
TNimType NTI107206; /* Month */
TNimType NTI107208; /* WeekDay */
TNimType NTI107427; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */

N_NIMCALL(void, gettzname_107570)(TY107572* Result) {
{	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(((NI) 0))- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(((NI) 1))- 0]));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_107604)(void) {
	NI result;
{	result = 0;
	result = timezone;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_108048)(struct tm* tm, NIM_BOOL local, Timeinfo107410* Result) {
	Timeinfo107410 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI107410);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI107410);
	LOC1.second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.month = ((NU8) ((*tm).tm_mon));
	LOC1.year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.weekday = weekdays_108053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY107572 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_107570((&LOC10));
			LOC1.tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY107572 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_107570((&LOC12));
			LOC1.tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.tzname = copyString(((NimStringDesc*) &TMP73));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.timezone = gettimezone_107604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.timezone = ((NI) 0);
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI107410));
}

N_NIMCALL(void, getlocaltime_107477)(time_t t, Timeinfo107410* Result) {
	time_t a;
	struct tm* lt;
	a = t;
	lt = localtime((&a));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI107410));
	(*Result).Sup.m_type = (&NTI107410);
	tmtotimeinfo_108048((&(*lt)), NIM_TRUE, Result);
}

N_NIMCALL(time_t, gettime_107472)(void) {
	time_t result;
{	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	Timeinfo107410 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107410);
	LOC1 = 0;
	LOC1 = gettime_107472();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107410);
	getlocaltime_107477(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(ti.year);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI)(((NI) (ti.month)) + ((NI) 1)))), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.monthday)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	Timeinfo107410 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107410);
	LOC1 = 0;
	LOC1 = gettime_107472();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107410);
	getlocaltime_107477(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.hour)), ((NI) 2));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.minute)), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.second)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void) {
	tzset();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void) {
static TNimNode* TMP66[11];
static TNimNode* TMP67[12];
NI TMP69;
static char* NIM_CONST TMP68[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP70[7];
NI TMP72;
static char* NIM_CONST TMP71[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP11[33];
NTI107410.size = sizeof(Timeinfo107410);
NTI107410.kind = 17;
NTI107410.base = (&NTI4011);
TMP66[0] = &TMP11[1];
NTI107413.size = sizeof(NI);
NTI107413.kind = 20;
NTI107413.base = (&NTI108);
NTI107413.flags = 3;
TMP11[1].kind = 1;
TMP11[1].offset = offsetof(Timeinfo107410, second);
TMP11[1].typ = (&NTI107413);
TMP11[1].name = "second";
TMP66[1] = &TMP11[2];
NTI107416.size = sizeof(NI);
NTI107416.kind = 20;
NTI107416.base = (&NTI108);
NTI107416.flags = 3;
TMP11[2].kind = 1;
TMP11[2].offset = offsetof(Timeinfo107410, minute);
TMP11[2].typ = (&NTI107416);
TMP11[2].name = "minute";
TMP66[2] = &TMP11[3];
NTI107418.size = sizeof(NI);
NTI107418.kind = 20;
NTI107418.base = (&NTI108);
NTI107418.flags = 3;
TMP11[3].kind = 1;
TMP11[3].offset = offsetof(Timeinfo107410, hour);
TMP11[3].typ = (&NTI107418);
TMP11[3].name = "hour";
TMP66[3] = &TMP11[4];
NTI107421.size = sizeof(NI);
NTI107421.kind = 20;
NTI107421.base = (&NTI108);
NTI107421.flags = 3;
TMP11[4].kind = 1;
TMP11[4].offset = offsetof(Timeinfo107410, monthday);
TMP11[4].typ = (&NTI107421);
TMP11[4].name = "monthday";
TMP66[4] = &TMP11[5];
NTI107206.size = sizeof(NU8);
NTI107206.kind = 14;
NTI107206.base = 0;
NTI107206.flags = 3;
for (TMP69 = 0; TMP69 < 12; TMP69++) {
TMP11[TMP69+6].kind = 1;
TMP11[TMP69+6].offset = TMP69;
TMP11[TMP69+6].name = TMP68[TMP69];
TMP67[TMP69] = &TMP11[TMP69+6];
}
TMP11[18].len = 12; TMP11[18].kind = 2; TMP11[18].sons = &TMP67[0];
NTI107206.node = &TMP11[18];
TMP11[5].kind = 1;
TMP11[5].offset = offsetof(Timeinfo107410, month);
TMP11[5].typ = (&NTI107206);
TMP11[5].name = "month";
TMP66[5] = &TMP11[19];
TMP11[19].kind = 1;
TMP11[19].offset = offsetof(Timeinfo107410, year);
TMP11[19].typ = (&NTI108);
TMP11[19].name = "year";
TMP66[6] = &TMP11[20];
NTI107208.size = sizeof(NU8);
NTI107208.kind = 14;
NTI107208.base = 0;
NTI107208.flags = 3;
for (TMP72 = 0; TMP72 < 7; TMP72++) {
TMP11[TMP72+21].kind = 1;
TMP11[TMP72+21].offset = TMP72;
TMP11[TMP72+21].name = TMP71[TMP72];
TMP70[TMP72] = &TMP11[TMP72+21];
}
TMP11[28].len = 7; TMP11[28].kind = 2; TMP11[28].sons = &TMP70[0];
NTI107208.node = &TMP11[28];
TMP11[20].kind = 1;
TMP11[20].offset = offsetof(Timeinfo107410, weekday);
TMP11[20].typ = (&NTI107208);
TMP11[20].name = "weekday";
TMP66[7] = &TMP11[29];
NTI107427.size = sizeof(NI);
NTI107427.kind = 20;
NTI107427.base = (&NTI108);
NTI107427.flags = 3;
TMP11[29].kind = 1;
TMP11[29].offset = offsetof(Timeinfo107410, yearday);
TMP11[29].typ = (&NTI107427);
TMP11[29].name = "yearday";
TMP66[8] = &TMP11[30];
TMP11[30].kind = 1;
TMP11[30].offset = offsetof(Timeinfo107410, isdst);
TMP11[30].typ = (&NTI138);
TMP11[30].name = "isDST";
TMP66[9] = &TMP11[31];
TMP11[31].kind = 1;
TMP11[31].offset = offsetof(Timeinfo107410, tzname);
TMP11[31].typ = (&NTI149);
TMP11[31].name = "tzname";
TMP66[10] = &TMP11[32];
TMP11[32].kind = 1;
TMP11[32].offset = offsetof(Timeinfo107410, timezone);
TMP11[32].typ = (&NTI108);
TMP11[32].name = "timezone";
TMP11[0].len = 11; TMP11[0].kind = 2; TMP11[0].sons = &TMP66[0];
NTI107410.node = &TMP11[0];
}

